// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: addresses.sql

package usersdb

import (
	"context"

	"github.com/google/uuid"
)

const clearDefaultForUser = `-- name: ClearDefaultForUser :exec
UPDATE users.addresses
SET is_default = FALSE, updated_at = NOW()
WHERE user_id = $1 AND is_default = TRUE
`

// ClearDefault is run inside the same tx as SetDefault / CreateAddress(is_default=true)
// to release the partial-unique-index slot before another row claims it.
func (q *Queries) ClearDefaultForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultForUser, userID)
	return err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO users.addresses (
    user_id, address, latitude, longitude, is_default
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, address, latitude, longitude, is_default, created_at, updated_at
`

type CreateAddressParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Address   string    `json:"address"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	IsDefault bool      `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (UsersAddress, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.IsDefault,
	)
	var i UsersAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :execrows
DELETE FROM users.addresses
WHERE id = $1 AND user_id = $2
`

type DeleteAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, address, latitude, longitude, is_default, created_at, updated_at FROM users.addresses
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetAddressByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAddressByID(ctx context.Context, arg GetAddressByIDParams) (UsersAddress, error) {
	row := q.db.QueryRow(ctx, getAddressByID, arg.ID, arg.UserID)
	var i UsersAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultAddress = `-- name: GetDefaultAddress :one
SELECT id, user_id, address, latitude, longitude, is_default, created_at, updated_at FROM users.addresses
WHERE user_id = $1 AND is_default = TRUE
LIMIT 1
`

func (q *Queries) GetDefaultAddress(ctx context.Context, userID uuid.UUID) (UsersAddress, error) {
	row := q.db.QueryRow(ctx, getDefaultAddress, userID)
	var i UsersAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT id, user_id, address, latitude, longitude, is_default, created_at, updated_at FROM users.addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListAddressesByUser(ctx context.Context, userID uuid.UUID) ([]UsersAddress, error) {
	rows, err := q.db.Query(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersAddress{}
	for rows.Next() {
		var i UsersAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultAddress = `-- name: SetDefaultAddress :one
UPDATE users.addresses
SET is_default = TRUE, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, address, latitude, longitude, is_default, created_at, updated_at
`

type SetDefaultAddressParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (UsersAddress, error) {
	row := q.db.QueryRow(ctx, setDefaultAddress, arg.ID, arg.UserID)
	var i UsersAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE users.addresses
SET
    address    = $1,
    latitude   = $2,
    longitude  = $3,
    updated_at = NOW()
WHERE id = $4 AND user_id = $5
RETURNING id, user_id, address, latitude, longitude, is_default, created_at, updated_at
`

type UpdateAddressParams struct {
	Address   string    `json:"address"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
}

// Service loads the current row, merges fields from the PATCH request, then
// passes the full new values back here. Keeps lat/long NOT NULL without
// needing nullable-narg gymnastics in sqlc.
func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UsersAddress, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.ID,
		arg.UserID,
	)
	var i UsersAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
