// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package usersdb

import (
	"context"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO users.profiles (
    user_id, display_name, phone, address, avatar_url, bio
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, display_name, phone, address, avatar_url, bio, created_at, updated_at
`

type CreateProfileParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Phone       *string   `json:"phone"`
	Address     *string   `json:"address"`
	AvatarUrl   *string   `json:"avatar_url"`
	Bio         *string   `json:"bio"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (UsersProfile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.DisplayName,
		arg.Phone,
		arg.Address,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i UsersProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Phone,
		&i.Address,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT id, user_id, display_name, phone, address, avatar_url, bio, created_at, updated_at FROM users.profiles WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetProfileByUserID(ctx context.Context, userID uuid.UUID) (UsersProfile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i UsersProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Phone,
		&i.Address,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users.profiles
SET
    display_name = $1,
    phone        = COALESCE($2, phone),
    address      = COALESCE($3, address),
    avatar_url   = COALESCE($4, avatar_url),
    bio          = COALESCE($5, bio),
    updated_at   = now()
WHERE user_id = $6
RETURNING id, user_id, display_name, phone, address, avatar_url, bio, created_at, updated_at
`

type UpdateProfileParams struct {
	DisplayName string    `json:"display_name"`
	Phone       *string   `json:"phone"`
	Address     *string   `json:"address"`
	AvatarUrl   *string   `json:"avatar_url"`
	Bio         *string   `json:"bio"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UsersProfile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.DisplayName,
		arg.Phone,
		arg.Address,
		arg.AvatarUrl,
		arg.Bio,
		arg.UserID,
	)
	var i UsersProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Phone,
		&i.Address,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
