// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: redemptions.sql

package voucherdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createRedemption = `-- name: CreateRedemption :one
INSERT INTO voucher.redemptions (voucher_id, user_id, order_id, discount_amount)
VALUES ($1, $2, $3, $4)
RETURNING id, voucher_id, user_id, order_id, discount_amount, redeemed_at
`

type CreateRedemptionParams struct {
	VoucherID      uuid.UUID       `json:"voucher_id"`
	UserID         uuid.UUID       `json:"user_id"`
	OrderID        uuid.UUID       `json:"order_id"`
	DiscountAmount decimal.Decimal `json:"discount_amount"`
}

// Inserted inside /orders/confirm's tx. Unique violation on
// (voucher_id, user_id) → caller rolls back the whole tx and returns 409.
func (q *Queries) CreateRedemption(ctx context.Context, arg CreateRedemptionParams) (VoucherRedemption, error) {
	row := q.db.QueryRow(ctx, createRedemption,
		arg.VoucherID,
		arg.UserID,
		arg.OrderID,
		arg.DiscountAmount,
	)
	var i VoucherRedemption
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.UserID,
		&i.OrderID,
		&i.DiscountAmount,
		&i.RedeemedAt,
	)
	return i, err
}

const getRedemptionByUserVoucher = `-- name: GetRedemptionByUserVoucher :one
SELECT id, voucher_id, user_id, order_id, discount_amount, redeemed_at FROM voucher.redemptions
WHERE voucher_id = $1 AND user_id = $2
LIMIT 1
`

type GetRedemptionByUserVoucherParams struct {
	VoucherID uuid.UUID `json:"voucher_id"`
	UserID    uuid.UUID `json:"user_id"`
}

// Informational pre-check used at /orders/select-branch so we can surface
// VOUCHER_ALREADY_USED before the user clicks Confirm. The CreateRedemption
// unique constraint is what actually enforces the rule.
func (q *Queries) GetRedemptionByUserVoucher(ctx context.Context, arg GetRedemptionByUserVoucherParams) (VoucherRedemption, error) {
	row := q.db.QueryRow(ctx, getRedemptionByUserVoucher, arg.VoucherID, arg.UserID)
	var i VoucherRedemption
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.UserID,
		&i.OrderID,
		&i.DiscountAmount,
		&i.RedeemedAt,
	)
	return i, err
}
