// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vouchers.sql

package voucherdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countVouchers = `-- name: CountVouchers :one
SELECT COUNT(*) FROM voucher.vouchers
WHERE (NOT $1::boolean OR is_active = $2::boolean)
`

type CountVouchersParams struct {
	FilterActive bool `json:"filter_active"`
	IsActive     bool `json:"is_active"`
}

func (q *Queries) CountVouchers(ctx context.Context, arg CountVouchersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVouchers, arg.FilterActive, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO voucher.vouchers (
    code, discount_percent, max_discount, min_subtotal,
    valid_from, valid_to, is_active, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $8
)
RETURNING id, code, discount_percent, max_discount, min_subtotal, valid_from, valid_to, is_active, created_at, created_by, updated_at, updated_by
`

type CreateVoucherParams struct {
	Code            string           `json:"code"`
	DiscountPercent int16            `json:"discount_percent"`
	MaxDiscount     *decimal.Decimal `json:"max_discount"`
	MinSubtotal     *decimal.Decimal `json:"min_subtotal"`
	ValidFrom       time.Time        `json:"valid_from"`
	ValidTo         time.Time        `json:"valid_to"`
	IsActive        bool             `json:"is_active"`
	CreatedBy       *uuid.UUID       `json:"created_by"`
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (VoucherVoucher, error) {
	row := q.db.QueryRow(ctx, createVoucher,
		arg.Code,
		arg.DiscountPercent,
		arg.MaxDiscount,
		arg.MinSubtotal,
		arg.ValidFrom,
		arg.ValidTo,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i VoucherVoucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercent,
		&i.MaxDiscount,
		&i.MinSubtotal,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getVoucherByCode = `-- name: GetVoucherByCode :one
SELECT id, code, discount_percent, max_discount, min_subtotal, valid_from, valid_to, is_active, created_at, created_by, updated_at, updated_by FROM voucher.vouchers WHERE code = $1 LIMIT 1
`

func (q *Queries) GetVoucherByCode(ctx context.Context, code string) (VoucherVoucher, error) {
	row := q.db.QueryRow(ctx, getVoucherByCode, code)
	var i VoucherVoucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercent,
		&i.MaxDiscount,
		&i.MinSubtotal,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getVoucherByID = `-- name: GetVoucherByID :one
SELECT id, code, discount_percent, max_discount, min_subtotal, valid_from, valid_to, is_active, created_at, created_by, updated_at, updated_by FROM voucher.vouchers WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVoucherByID(ctx context.Context, id uuid.UUID) (VoucherVoucher, error) {
	row := q.db.QueryRow(ctx, getVoucherByID, id)
	var i VoucherVoucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercent,
		&i.MaxDiscount,
		&i.MinSubtotal,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listVouchers = `-- name: ListVouchers :many
SELECT id, code, discount_percent, max_discount, min_subtotal, valid_from, valid_to, is_active, created_at, created_by, updated_at, updated_by FROM voucher.vouchers
WHERE (NOT $1::boolean OR is_active = $2::boolean)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListVouchersParams struct {
	FilterActive bool  `json:"filter_active"`
	IsActive     bool  `json:"is_active"`
	Off          int32 `json:"off"`
	Lim          int32 `json:"lim"`
}

// Admin matrix view. The boolean "filter_active" picks whether to constrain
// by is_active; when false, the is_active argument is ignored.
func (q *Queries) ListVouchers(ctx context.Context, arg ListVouchersParams) ([]VoucherVoucher, error) {
	rows, err := q.db.Query(ctx, listVouchers,
		arg.FilterActive,
		arg.IsActive,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoucherVoucher{}
	for rows.Next() {
		var i VoucherVoucher
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.DiscountPercent,
			&i.MaxDiscount,
			&i.MinSubtotal,
			&i.ValidFrom,
			&i.ValidTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoucher = `-- name: UpdateVoucher :one
UPDATE voucher.vouchers
SET discount_percent = CASE WHEN $2::boolean
                            THEN $3::smallint
                            ELSE discount_percent END,
    max_discount     = CASE WHEN $4::boolean
                            THEN $5::numeric
                            ELSE max_discount END,
    min_subtotal     = CASE WHEN $6::boolean
                            THEN $7::numeric
                            ELSE min_subtotal END,
    valid_from       = CASE WHEN $8::boolean
                            THEN $9::timestamptz
                            ELSE valid_from END,
    valid_to         = CASE WHEN $10::boolean
                            THEN $11::timestamptz
                            ELSE valid_to END,
    is_active        = CASE WHEN $12::boolean
                            THEN $13::boolean
                            ELSE is_active END,
    updated_at       = NOW(),
    updated_by       = $14
WHERE id = $1
RETURNING id, code, discount_percent, max_discount, min_subtotal, valid_from, valid_to, is_active, created_at, created_by, updated_at, updated_by
`

type UpdateVoucherParams struct {
	ID              uuid.UUID      `json:"id"`
	SetPercent      bool           `json:"set_percent"`
	DiscountPercent int16          `json:"discount_percent"`
	SetMaxDiscount  bool           `json:"set_max_discount"`
	MaxDiscount     pgtype.Numeric `json:"max_discount"`
	SetMinSubtotal  bool           `json:"set_min_subtotal"`
	MinSubtotal     pgtype.Numeric `json:"min_subtotal"`
	SetValidFrom    bool           `json:"set_valid_from"`
	ValidFrom       time.Time      `json:"valid_from"`
	SetValidTo      bool           `json:"set_valid_to"`
	ValidTo         time.Time      `json:"valid_to"`
	SetIsActive     bool           `json:"set_is_active"`
	IsActive        bool           `json:"is_active"`
	UpdatedBy       *uuid.UUID     `json:"updated_by"`
}

// Patch fields on a voucher. The boolean "set_*" flags pick whether the
// corresponding column is overwritten or left as-is. updated_by/updated_at
// always change so audit trail is correct even on a no-op call.
func (q *Queries) UpdateVoucher(ctx context.Context, arg UpdateVoucherParams) (VoucherVoucher, error) {
	row := q.db.QueryRow(ctx, updateVoucher,
		arg.ID,
		arg.SetPercent,
		arg.DiscountPercent,
		arg.SetMaxDiscount,
		arg.MaxDiscount,
		arg.SetMinSubtotal,
		arg.MinSubtotal,
		arg.SetValidFrom,
		arg.ValidFrom,
		arg.SetValidTo,
		arg.ValidTo,
		arg.SetIsActive,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i VoucherVoucher
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DiscountPercent,
		&i.MaxDiscount,
		&i.MinSubtotal,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
