// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procurement.sql

package procurementdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createPOItem = `-- name: CreatePOItem :one
INSERT INTO procurement.po_items (
    po_id, product_id, quantity, unit_price
) VALUES ($1, $2, $3, $4)
RETURNING id, po_id, product_id, quantity, unit_price, total_price
`

type CreatePOItemParams struct {
	PoID      uuid.UUID       `json:"po_id"`
	ProductID uuid.UUID       `json:"product_id"`
	Quantity  decimal.Decimal `json:"quantity"`
	UnitPrice decimal.Decimal `json:"unit_price"`
}

func (q *Queries) CreatePOItem(ctx context.Context, arg CreatePOItemParams) (ProcurementPoItem, error) {
	row := q.db.QueryRow(ctx, createPOItem,
		arg.PoID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i ProcurementPoItem
	err := row.Scan(
		&i.ID,
		&i.PoID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
	)
	return i, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO procurement.purchase_orders (
    supplier_id, branch_id, status, total_amount, note, created_by, updated_by
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, supplier_id, branch_id, status, total_amount, note, deleted_at, created_at, updated_at, created_by, updated_by, version
`

type CreatePurchaseOrderParams struct {
	SupplierID  uuid.UUID       `json:"supplier_id"`
	BranchID    uuid.UUID       `json:"branch_id"`
	Status      string          `json:"status"`
	TotalAmount decimal.Decimal `json:"total_amount"`
	Note        *string         `json:"note"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (ProcurementPurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.SupplierID,
		arg.BranchID,
		arg.Status,
		arg.TotalAmount,
		arg.Note,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ProcurementPurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.BranchID,
		&i.Status,
		&i.TotalAmount,
		&i.Note,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}

const getPOItems = `-- name: GetPOItems :many
SELECT id, po_id, product_id, quantity, unit_price, total_price FROM procurement.po_items
WHERE po_id = $1
`

func (q *Queries) GetPOItems(ctx context.Context, poID uuid.UUID) ([]ProcurementPoItem, error) {
	rows, err := q.db.Query(ctx, getPOItems, poID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcurementPoItem{}
	for rows.Next() {
		var i ProcurementPoItem
		if err := rows.Scan(
			&i.ID,
			&i.PoID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT id, supplier_id, branch_id, status, total_amount, note, deleted_at, created_at, updated_at, created_by, updated_by, version FROM procurement.purchase_orders
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPurchaseOrder(ctx context.Context, id uuid.UUID) (ProcurementPurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, id)
	var i ProcurementPurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.BranchID,
		&i.Status,
		&i.TotalAmount,
		&i.Note,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}

const listPurchaseOrdersByBranch = `-- name: ListPurchaseOrdersByBranch :many
SELECT id, supplier_id, branch_id, status, total_amount, note, deleted_at, created_at, updated_at, created_by, updated_by, version FROM procurement.purchase_orders
WHERE branch_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPurchaseOrdersByBranch(ctx context.Context, branchID uuid.UUID) ([]ProcurementPurchaseOrder, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrdersByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcurementPurchaseOrder{}
	for rows.Next() {
		var i ProcurementPurchaseOrder
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.BranchID,
			&i.Status,
			&i.TotalAmount,
			&i.Note,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePOStatus = `-- name: UpdatePOStatus :one
UPDATE procurement.purchase_orders
SET status = $2, version = version + 1, updated_at = NOW(), updated_by = $3
WHERE id = $1 AND version = $4 AND deleted_at IS NULL
RETURNING id, supplier_id, branch_id, status, total_amount, note, deleted_at, created_at, updated_at, created_by, updated_by, version
`

type UpdatePOStatusParams struct {
	ID        uuid.UUID  `json:"id"`
	Status    string     `json:"status"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	Version   int32      `json:"version"`
}

func (q *Queries) UpdatePOStatus(ctx context.Context, arg UpdatePOStatusParams) (ProcurementPurchaseOrder, error) {
	row := q.db.QueryRow(ctx, updatePOStatus, arg.ID, arg.Status, arg.UpdatedBy, arg.Version)
	var i ProcurementPurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.SupplierID,
		&i.BranchID,
		&i.Status,
		&i.TotalAmount,
		&i.Note,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}

const listAllPurchaseOrders = `-- name: ListAllPurchaseOrders :many
SELECT id, supplier_id, branch_id, status, total_amount, note, deleted_at, created_at, updated_at, created_by, updated_by, version FROM procurement.purchase_orders
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAllPurchaseOrders(ctx context.Context) ([]ProcurementPurchaseOrder, error) {
	rows, err := q.db.Query(ctx, listAllPurchaseOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcurementPurchaseOrder{}
	for rows.Next() {
		var i ProcurementPurchaseOrder
		if err := rows.Scan(
			&i.ID,
			&i.SupplierID,
			&i.BranchID,
			&i.Status,
			&i.TotalAmount,
			&i.Note,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
