// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: suppliers.sql

package procurementdb

import (
	"context"

	"github.com/google/uuid"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO procurement.suppliers (
    name, contact_info, region, created_by, updated_by
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, contact_info, region, is_active, deleted_at, created_at, updated_at, created_by, updated_by
`

type CreateSupplierParams struct {
	Name        string     `json:"name"`
	ContactInfo *string    `json:"contact_info"`
	Region      string     `json:"region"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (ProcurementSupplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.Name,
		arg.ContactInfo,
		arg.Region,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ProcurementSupplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactInfo,
		&i.Region,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, name, contact_info, region, is_active, deleted_at, created_at, updated_at, created_by, updated_by FROM procurement.suppliers
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSupplierByID(ctx context.Context, id uuid.UUID) (ProcurementSupplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i ProcurementSupplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactInfo,
		&i.Region,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listSuppliersByRegion = `-- name: ListSuppliersByRegion :many
SELECT id, name, contact_info, region, is_active, deleted_at, created_at, updated_at, created_by, updated_by FROM procurement.suppliers
WHERE region = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListSuppliersByRegion(ctx context.Context, region string) ([]ProcurementSupplier, error) {
	rows, err := q.db.Query(ctx, listSuppliersByRegion, region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcurementSupplier{}
	for rows.Next() {
		var i ProcurementSupplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactInfo,
			&i.Region,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSupplier = `-- name: SoftDeleteSupplier :exec
UPDATE procurement.suppliers
SET deleted_at = NOW(), updated_by = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeleteSupplierParams struct {
	ID        uuid.UUID  `json:"id"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteSupplier(ctx context.Context, arg SoftDeleteSupplierParams) error {
	_, err := q.db.Exec(ctx, softDeleteSupplier, arg.ID, arg.UpdatedBy)
	return err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE procurement.suppliers
SET name = $2, contact_info = $3, region = $4, is_active = $5, updated_at = NOW(), updated_by = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, contact_info, region, is_active, deleted_at, created_at, updated_at, created_by, updated_by
`

type UpdateSupplierParams struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	ContactInfo *string    `json:"contact_info"`
	Region      string     `json:"region"`
	IsActive    bool       `json:"is_active"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (ProcurementSupplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.ID,
		arg.Name,
		arg.ContactInfo,
		arg.Region,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i ProcurementSupplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactInfo,
		&i.Region,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
