// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package membershipdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getMembershipByUserID = `-- name: GetMembershipByUserID :one
SELECT user_id, tier, total_spent, updated_at FROM users.memberships WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetMembershipByUserID(ctx context.Context, userID uuid.UUID) (UsersMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserID, userID)
	var i UsersMembership
	err := row.Scan(
		&i.UserID,
		&i.Tier,
		&i.TotalSpent,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMembershipTier = `-- name: UpdateMembershipTier :one
UPDATE users.memberships
SET tier = $2, updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, tier, total_spent, updated_at
`

type UpdateMembershipTierParams struct {
	UserID uuid.UUID `json:"user_id"`
	Tier   string    `json:"tier"`
}

// Idempotent setter for the derived label. Run in the same tx as
// UpsertMembershipSpend so a tier promotion is visible atomically with the
// spend increment.
func (q *Queries) UpdateMembershipTier(ctx context.Context, arg UpdateMembershipTierParams) (UsersMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipTier, arg.UserID, arg.Tier)
	var i UsersMembership
	err := row.Scan(
		&i.UserID,
		&i.Tier,
		&i.TotalSpent,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMembershipSpend = `-- name: UpsertMembershipSpend :one
INSERT INTO users.memberships (user_id, total_spent)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET total_spent = users.memberships.total_spent + EXCLUDED.total_spent,
    updated_at  = NOW()
RETURNING user_id, tier, total_spent, updated_at
`

type UpsertMembershipSpendParams struct {
	UserID     uuid.UUID       `json:"user_id"`
	TotalSpent decimal.Decimal `json:"total_spent"`
}

// Atomic increment used by /orders/confirm. On conflict, total_spent grows
// by EXCLUDED.total_spent (the delta the caller passed). Tier is NOT touched
// here — service recomputes it from the new total via a pure Go function and
// calls UpdateMembershipTier in the same tx.
func (q *Queries) UpsertMembershipSpend(ctx context.Context, arg UpsertMembershipSpendParams) (UsersMembership, error) {
	row := q.db.QueryRow(ctx, upsertMembershipSpend, arg.UserID, arg.TotalSpent)
	var i UsersMembership
	err := row.Scan(
		&i.UserID,
		&i.Tier,
		&i.TotalSpent,
		&i.UpdatedAt,
	)
	return i, err
}
