// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package authdb

import (
	"context"

	"github.com/google/uuid"
)

const assignRoleByName = `-- name: AssignRoleByName :exec
INSERT INTO auth.user_roles (user_id, role_id)
SELECT $1, id FROM auth.roles WHERE name = $2
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignRoleByNameParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) AssignRoleByName(ctx context.Context, arg AssignRoleByNameParams) error {
	_, err := q.db.Exec(ctx, assignRoleByName, arg.UserID, arg.Name)
	return err
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT name FROM auth.roles
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsByRole = `-- name: GetPermissionsByRole :many
SELECT p.name
FROM auth.permissions p
JOIN auth.role_permissions rp ON p.id = rp.permission_id
JOIN auth.roles r ON r.id = rp.role_id
WHERE r.name = $1
`

func (q *Queries) GetPermissionsByRole(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRole, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleByName = `-- name: RemoveRoleByName :exec
DELETE FROM auth.user_roles
WHERE user_id = $1
  AND role_id = (SELECT id FROM auth.roles WHERE name = $2)
`

type RemoveRoleByNameParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) RemoveRoleByName(ctx context.Context, arg RemoveRoleByNameParams) error {
	_, err := q.db.Exec(ctx, removeRoleByName, arg.UserID, arg.Name)
	return err
}
