// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package authdb

import (
	"context"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE auth.users
SET email_verified = true, is_active = true
where id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const createAuthCredential = `-- name: CreateAuthCredential :one
INSERT INTO auth.auth_credentials (
    user_id, password_hash
) VALUES ($1, $2)
    RETURNING id, user_id, password_hash, password_changed_at, created_at, updated_at
`

type CreateAuthCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateAuthCredential(ctx context.Context, arg CreateAuthCredentialParams) (AuthAuthCredential, error) {
	row := q.db.QueryRow(ctx, createAuthCredential, arg.UserID, arg.PasswordHash)
	var i AuthAuthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (
    email, email_verified, is_active
) VALUES ($1, $2, $3)
    RETURNING id, email, email_verified, is_active, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	IsActive      bool   `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.EmailVerified, arg.IsActive)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified, is_active, deleted_at, created_at, updated_at FROM auth.users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified, is_active, deleted_at, created_at, updated_at FROM auth.users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.name
FROM auth.roles r
JOIN auth.user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithCredentialsByEmail = `-- name: GetUserWithCredentialsByEmail :one
SELECT u.id, email, password_hash
FROM auth.users u
JOIN auth.auth_credentials au
ON u.id = au.user_id
WHERE email = $1 and is_active = true and email_verified = true
LIMIT 1
`

type GetUserWithCredentialsByEmailRow struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) GetUserWithCredentialsByEmail(ctx context.Context, email string) (GetUserWithCredentialsByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserWithCredentialsByEmail, email)
	var i GetUserWithCredentialsByEmailRow
	err := row.Scan(&i.ID, &i.Email, &i.PasswordHash)
	return i, err
}
