// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package authdb

import (
	"context"

	"github.com/google/uuid"
)

const createAuthCredential = `-- name: CreateAuthCredential :one
INSERT INTO auth.auth_credentials (
    user_id, password_hash
) VALUES ($1, $2)
RETURNING id, user_id, password_hash, password_changed_at, created_at, updated_at
`

type CreateAuthCredentialParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateAuthCredential(ctx context.Context, arg CreateAuthCredentialParams) (AuthAuthCredential, error) {
	row := q.db.QueryRow(ctx, createAuthCredential, arg.UserID, arg.PasswordHash)
	var i AuthAuthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (
    email, email_verified, is_active
) VALUES ($1, $2, $3)
RETURNING id, email, email_verified, is_active, deleted_at, created_at, updated_at
`

type CreateUserParams struct {
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	IsActive      bool   `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.EmailVerified, arg.IsActive)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
