// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branches.sql

package statisticsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getBranchKPIs = `-- name: GetBranchKPIs :one
SELECT
    COUNT(*) FILTER (
        WHERE placed_at >= date_trunc('day',
              now() AT TIME ZONE 'Asia/Ho_Chi_Minh') AT TIME ZONE 'Asia/Ho_Chi_Minh'
    )::bigint AS orders_today,
    COALESCE(SUM(total) FILTER (
        WHERE placed_at >= date_trunc('day',
              now() AT TIME ZONE 'Asia/Ho_Chi_Minh') AT TIME ZONE 'Asia/Ho_Chi_Minh'
    ), 0)::numeric AS revenue_today,

    COUNT(*) FILTER (
        WHERE placed_at >= date_trunc('week',
              now() AT TIME ZONE 'Asia/Ho_Chi_Minh') AT TIME ZONE 'Asia/Ho_Chi_Minh'
    )::bigint AS orders_week,
    COALESCE(SUM(total) FILTER (
        WHERE placed_at >= date_trunc('week',
              now() AT TIME ZONE 'Asia/Ho_Chi_Minh') AT TIME ZONE 'Asia/Ho_Chi_Minh'
    ), 0)::numeric AS revenue_week,

    COUNT(*) FILTER (
        WHERE placed_at >= date_trunc('month',
              now() AT TIME ZONE 'Asia/Ho_Chi_Minh') AT TIME ZONE 'Asia/Ho_Chi_Minh'
    )::bigint AS orders_month,
    COALESCE(SUM(total) FILTER (
        WHERE placed_at >= date_trunc('month',
              now() AT TIME ZONE 'Asia/Ho_Chi_Minh') AT TIME ZONE 'Asia/Ho_Chi_Minh'
    ), 0)::numeric AS revenue_month,

    COUNT(*)::bigint                              AS orders_all,
    COALESCE(SUM(total), 0)::numeric              AS revenue_all,
    COUNT(DISTINCT user_id)::bigint               AS unique_customers
FROM orders.orders
WHERE branch_id = $1
`

type GetBranchKPIsRow struct {
	OrdersToday     int64           `json:"orders_today"`
	RevenueToday    decimal.Decimal `json:"revenue_today"`
	OrdersWeek      int64           `json:"orders_week"`
	RevenueWeek     decimal.Decimal `json:"revenue_week"`
	OrdersMonth     int64           `json:"orders_month"`
	RevenueMonth    decimal.Decimal `json:"revenue_month"`
	OrdersAll       int64           `json:"orders_all"`
	RevenueAll      decimal.Decimal `json:"revenue_all"`
	UniqueCustomers int64           `json:"unique_customers"`
}

// Single branch counters bundled with the calendar-aligned period filters
// (today / this week / this month, in Asia/Ho_Chi_Minh). The conversion
// pattern is: now() AT TIME ZONE → date_trunc → AT TIME ZONE, which produces
// a TIMESTAMPTZ at local-midnight that's directly comparable with placed_at.
func (q *Queries) GetBranchKPIs(ctx context.Context, branchID uuid.UUID) (GetBranchKPIsRow, error) {
	row := q.db.QueryRow(ctx, getBranchKPIs, branchID)
	var i GetBranchKPIsRow
	err := row.Scan(
		&i.OrdersToday,
		&i.RevenueToday,
		&i.OrdersWeek,
		&i.RevenueWeek,
		&i.OrdersMonth,
		&i.RevenueMonth,
		&i.OrdersAll,
		&i.RevenueAll,
		&i.UniqueCustomers,
	)
	return i, err
}

const getBranchSideCounts = `-- name: GetBranchSideCounts :one
SELECT
    COALESCE((SELECT b.name FROM branch.branches b WHERE b.id = $1), '')::text AS branch_name,
    (SELECT COUNT(*) FROM branch.branch_memberships
        WHERE branch_id = $1)::bigint AS staff_count,
    (SELECT COUNT(*) FROM product.branch_products
        WHERE branch_id = $1 AND is_active = TRUE)::bigint AS active_products
`

type GetBranchSideCountsRow struct {
	BranchName     string `json:"branch_name"`
	StaffCount     int64  `json:"staff_count"`
	ActiveProducts int64  `json:"active_products"`
}

// Slow-changing counts paired with the KPI bundle. Same row count regardless
// of order volume so it can sit next to the more dynamic numbers.
func (q *Queries) GetBranchSideCounts(ctx context.Context, id uuid.UUID) (GetBranchSideCountsRow, error) {
	row := q.db.QueryRow(ctx, getBranchSideCounts, id)
	var i GetBranchSideCountsRow
	err := row.Scan(&i.BranchName, &i.StaffCount, &i.ActiveProducts)
	return i, err
}

const listBranchStats = `-- name: ListBranchStats :many
SELECT
    b.id                                AS branch_id,
    b.name                              AS branch_name,
    COALESCE(o.order_count, 0)::bigint  AS order_count,
    COALESCE(o.revenue, 0)::numeric     AS revenue,
    COALESCE(s.staff_count, 0)::bigint  AS staff_count,
    COALESCE(bp.active_products, 0)::bigint AS active_products
FROM branch.branches b
LEFT JOIN (
    SELECT branch_id,
           COUNT(*)   AS order_count,
           SUM(total) AS revenue
    FROM orders.orders
    GROUP BY branch_id
) o ON o.branch_id = b.id
LEFT JOIN (
    SELECT branch_id, COUNT(*) AS staff_count
    FROM branch.branch_memberships
    GROUP BY branch_id
) s ON s.branch_id = b.id
LEFT JOIN (
    SELECT branch_id, COUNT(*) AS active_products
    FROM product.branch_products
    WHERE is_active = TRUE
    GROUP BY branch_id
) bp ON bp.branch_id = b.id
ORDER BY COALESCE(o.revenue, 0) DESC, b.name ASC
`

type ListBranchStatsRow struct {
	BranchID       uuid.UUID       `json:"branch_id"`
	BranchName     string          `json:"branch_name"`
	OrderCount     int64           `json:"order_count"`
	Revenue        decimal.Decimal `json:"revenue"`
	StaffCount     int64           `json:"staff_count"`
	ActiveProducts int64           `json:"active_products"`
}

// All branches with aggregated KPIs. LEFT JOINs preserve branches with no
// orders / no staff / no active products (they show as 0).
func (q *Queries) ListBranchStats(ctx context.Context) ([]ListBranchStatsRow, error) {
	rows, err := q.db.Query(ctx, listBranchStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchStatsRow{}
	for rows.Next() {
		var i ListBranchStatsRow
		if err := rows.Scan(
			&i.BranchID,
			&i.BranchName,
			&i.OrderCount,
			&i.Revenue,
			&i.StaffCount,
			&i.ActiveProducts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopProductsByBranch = `-- name: ListTopProductsByBranch :many
SELECT
    oi.product_id,
    oi.name_snap                AS name,
    SUM(oi.quantity)::bigint    AS qty_sold,
    SUM(oi.line_total)::numeric AS revenue
FROM orders.orders o
JOIN orders.order_items oi ON oi.order_id = o.id
WHERE o.branch_id = $1
GROUP BY oi.product_id, oi.name_snap
ORDER BY revenue DESC
LIMIT $2
`

type ListTopProductsByBranchParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	Limit    int32     `json:"limit"`
}

type ListTopProductsByBranchRow struct {
	ProductID uuid.UUID       `json:"product_id"`
	Name      string          `json:"name"`
	QtySold   int64           `json:"qty_sold"`
	Revenue   decimal.Decimal `json:"revenue"`
}

// Top sellers at one branch by revenue. name_snap is the historical name on
// the order line (so renamed-since-sold products still show under their
// original name, which is what the customer saw).
func (q *Queries) ListTopProductsByBranch(ctx context.Context, arg ListTopProductsByBranchParams) ([]ListTopProductsByBranchRow, error) {
	rows, err := q.db.Query(ctx, listTopProductsByBranch, arg.BranchID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopProductsByBranchRow{}
	for rows.Next() {
		var i ListTopProductsByBranchRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.QtySold,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
