// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overview.sql

package statisticsdb

import (
	"context"

	"github.com/shopspring/decimal"
)

const getOverview = `-- name: GetOverview :one
SELECT
    (SELECT COUNT(*) FROM auth.users u
       JOIN auth.user_roles ur ON ur.user_id = u.id
       JOIN auth.roles r       ON r.id      = ur.role_id
       WHERE r.name = 'customer')                              AS total_customers,
    (SELECT COUNT(*) FROM branch.branches)                     AS total_branches,
    (SELECT COUNT(*) FROM product.products
       WHERE deleted_at IS NULL)                               AS total_products,
    (SELECT COUNT(*) FROM orders.orders)                       AS total_orders,
    (SELECT COALESCE(SUM(total), 0)::numeric FROM orders.orders)          AS total_revenue,
    (SELECT COALESCE(SUM(discount_total), 0)::numeric FROM orders.orders) AS total_discount,
    (SELECT COUNT(*) FROM voucher.redemptions)                 AS vouchers_redeemed,
    (SELECT COUNT(*) FROM users.memberships WHERE tier = 'BRONZE') AS bronze_users,
    (SELECT COUNT(*) FROM users.memberships WHERE tier = 'SILVER') AS silver_users,
    (SELECT COUNT(*) FROM users.memberships WHERE tier = 'GOLD')   AS gold_users
`

type GetOverviewRow struct {
	TotalCustomers   int64           `json:"total_customers"`
	TotalBranches    int64           `json:"total_branches"`
	TotalProducts    int64           `json:"total_products"`
	TotalOrders      int64           `json:"total_orders"`
	TotalRevenue     decimal.Decimal `json:"total_revenue"`
	TotalDiscount    decimal.Decimal `json:"total_discount"`
	VouchersRedeemed int64           `json:"vouchers_redeemed"`
	BronzeUsers      int64           `json:"bronze_users"`
	SilverUsers      int64           `json:"silver_users"`
	GoldUsers        int64           `json:"gold_users"`
}

// Top-level KPI bundle for the super_admin dashboard. Subqueries (instead of
// a giant CROSS JOIN) keep each count independent and self-explanatory; cost
// is negligible at this data scale.
func (q *Queries) GetOverview(ctx context.Context) (GetOverviewRow, error) {
	row := q.db.QueryRow(ctx, getOverview)
	var i GetOverviewRow
	err := row.Scan(
		&i.TotalCustomers,
		&i.TotalBranches,
		&i.TotalProducts,
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.TotalDiscount,
		&i.VouchersRedeemed,
		&i.BronzeUsers,
		&i.SilverUsers,
		&i.GoldUsers,
	)
	return i, err
}
