// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_timeseries.sql

package statisticsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getProductTimeseries = `-- name: GetProductTimeseries :many
WITH params AS (
    SELECT
        $1::text      AS gran,
        $2::uuid       AS pid,
        $3::timestamptz AS from_t,
        $4::timestamptz   AS to_t,
        $5::uuid       AS bid
),
buckets AS (
    SELECT generate_series(
        date_trunc(p.gran, p.from_t AT TIME ZONE 'Asia/Ho_Chi_Minh')
            AT TIME ZONE 'Asia/Ho_Chi_Minh',
        date_trunc(p.gran, p.to_t   AT TIME ZONE 'Asia/Ho_Chi_Minh')
            AT TIME ZONE 'Asia/Ho_Chi_Minh',
        ('1 ' || p.gran)::interval
    ) AS bucket_start
    FROM params p
)
SELECT
    b.bucket_start::timestamptz             AS bucket_start,
    COALESCE(SUM(oi.quantity),   0)::bigint AS qty_sold,
    COALESCE(SUM(oi.line_total), 0)::numeric AS revenue
FROM buckets b
CROSS JOIN params p
LEFT JOIN orders.orders o
    ON o.placed_at >= b.bucket_start
   AND o.placed_at <  b.bucket_start + ('1 ' || p.gran)::interval
   AND (p.bid IS NULL OR o.branch_id = p.bid)
LEFT JOIN orders.order_items oi
    ON oi.order_id   = o.id
   AND oi.product_id = p.pid
GROUP BY b.bucket_start
ORDER BY b.bucket_start
`

type GetProductTimeseriesParams struct {
	Granularity string     `json:"granularity"`
	ProductID   uuid.UUID  `json:"product_id"`
	FromTime    time.Time  `json:"from_time"`
	ToTime      time.Time  `json:"to_time"`
	BranchID    *uuid.UUID `json:"branch_id"`
}

type GetProductTimeseriesRow struct {
	BucketStart time.Time       `json:"bucket_start"`
	QtySold     int64           `json:"qty_sold"`
	Revenue     decimal.Decimal `json:"revenue"`
}

// Chart-friendly time-series of units sold (and revenue) for ONE product.
// Same shape + zero-fill behavior as GetOrderTimeseries, but aggregates over
// orders.order_items filtered by product_id. branch_id is optional —
// branch_manager callers will have it forced to their own; admin/product
// manager can omit it for all-branches numbers.
func (q *Queries) GetProductTimeseries(ctx context.Context, arg GetProductTimeseriesParams) ([]GetProductTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, getProductTimeseries,
		arg.Granularity,
		arg.ProductID,
		arg.FromTime,
		arg.ToTime,
		arg.BranchID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductTimeseriesRow{}
	for rows.Next() {
		var i GetProductTimeseriesRow
		if err := rows.Scan(&i.BucketStart, &i.QtySold, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
