// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package statisticsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countProductStats = `-- name: CountProductStats :one
SELECT COUNT(*) FROM product.products WHERE deleted_at IS NULL
`

func (q *Queries) CountProductStats(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductStats)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listProductStats = `-- name: ListProductStats :many
SELECT
    p.id, p.name, p.slug, p.price,
    COALESCE(s.qty_sold, 0)::bigint        AS qty_sold,
    COALESCE(s.revenue, 0)::numeric        AS revenue,
    COALESCE(b.branches_active, 0)::bigint AS branches_active,
    COALESCE(b.total_stock, 0)::bigint     AS total_stock
FROM product.products p
LEFT JOIN (
    SELECT product_id,
           SUM(quantity)   AS qty_sold,
           SUM(line_total) AS revenue
    FROM orders.order_items
    GROUP BY product_id
) s ON s.product_id = p.id
LEFT JOIN (
    SELECT product_id,
           COUNT(*) FILTER (WHERE is_active) AS branches_active,
           SUM(quantity)                     AS total_stock
    FROM product.branch_products
    GROUP BY product_id
) b ON b.product_id = p.id
WHERE p.deleted_at IS NULL
ORDER BY COALESCE(s.revenue, 0) DESC, p.name ASC
LIMIT $1 OFFSET $2
`

type ListProductStatsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductStatsRow struct {
	ID             uuid.UUID       `json:"id"`
	Name           string          `json:"name"`
	Slug           string          `json:"slug"`
	Price          decimal.Decimal `json:"price"`
	QtySold        int64           `json:"qty_sold"`
	Revenue        decimal.Decimal `json:"revenue"`
	BranchesActive int64           `json:"branches_active"`
	TotalStock     int64           `json:"total_stock"`
}

// Per-product breakdown sorted by revenue desc. LEFT JOINs preserve products
// that have never sold (qty_sold=0, revenue=0) and products inactive at every
// branch (branches_active=0, total_stock=0).
func (q *Queries) ListProductStats(ctx context.Context, arg ListProductStatsParams) ([]ListProductStatsRow, error) {
	rows, err := q.db.Query(ctx, listProductStats, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductStatsRow{}
	for rows.Next() {
		var i ListProductStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Price,
			&i.QtySold,
			&i.Revenue,
			&i.BranchesActive,
			&i.TotalStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
