// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timeseries.sql

package statisticsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getOrderTimeseries = `-- name: GetOrderTimeseries :many
WITH params AS (
    SELECT
        $1::text     AS gran,
        $2::timestamptz AS from_t,
        $3::timestamptz   AS to_t,
        $4::uuid       AS bid
),
buckets AS (
    SELECT generate_series(
        date_trunc(p.gran, p.from_t AT TIME ZONE 'Asia/Ho_Chi_Minh')
            AT TIME ZONE 'Asia/Ho_Chi_Minh',
        date_trunc(p.gran, p.to_t   AT TIME ZONE 'Asia/Ho_Chi_Minh')
            AT TIME ZONE 'Asia/Ho_Chi_Minh',
        ('1 ' || p.gran)::interval
    ) AS bucket_start
    FROM params p
)
SELECT
    b.bucket_start::timestamptz         AS bucket_start,
    COUNT(o.id)::bigint                 AS orders,
    COALESCE(SUM(o.total), 0)::numeric  AS revenue
FROM buckets b
CROSS JOIN params p
LEFT JOIN orders.orders o
    ON o.placed_at >= b.bucket_start
   AND o.placed_at <  b.bucket_start + ('1 ' || p.gran)::interval
   AND (p.bid IS NULL OR o.branch_id = p.bid)
GROUP BY b.bucket_start
ORDER BY b.bucket_start
`

type GetOrderTimeseriesParams struct {
	Granularity string     `json:"granularity"`
	FromTime    time.Time  `json:"from_time"`
	ToTime      time.Time  `json:"to_time"`
	BranchID    *uuid.UUID `json:"branch_id"`
}

type GetOrderTimeseriesRow struct {
	BucketStart time.Time       `json:"bucket_start"`
	Orders      int64           `json:"orders"`
	Revenue     decimal.Decimal `json:"revenue"`
}

// Chart-friendly time-series of orders.placed_at, parametric on granularity.
// Buckets are calendar-aligned in Asia/Ho_Chi_Minh.
//
// granularity is one of {day, week, month, year}. The handler whitelists the
// string before it reaches SQL — never pass user input straight through.
//
// generate_series gives one row per bucket inside [from_time, to_time],
// which guarantees zero-filled output even on days with no orders. The
// LEFT JOIN then sums the matching orders for each bucket. branch_id is
// optional (NULL = all branches).
func (q *Queries) GetOrderTimeseries(ctx context.Context, arg GetOrderTimeseriesParams) ([]GetOrderTimeseriesRow, error) {
	rows, err := q.db.Query(ctx, getOrderTimeseries,
		arg.Granularity,
		arg.FromTime,
		arg.ToTime,
		arg.BranchID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrderTimeseriesRow{}
	for rows.Next() {
		var i GetOrderTimeseriesRow
		if err := rows.Scan(&i.BucketStart, &i.Orders, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
