// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package profiledb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profile.profiles (
    user_id, display_name, avatar_url, bio
) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, display_name, avatar_url, bio, updated_at
`

type CreateProfileParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Bio         pgtype.Text `json:"bio"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (ProfileProfile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i ProfileProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.UpdatedAt,
	)
	return i, err
}
