// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package branchdb

import (
	"context"

	"github.com/google/uuid"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branch.branches (
    name, address, lat, lng, created_by, updated_by
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, address, lat, lng, status, created_at, deleted_at, updated_at, updated_by, created_by, region
`

type CreateBranchParams struct {
	Name      string     `json:"name"`
	Address   string     `json:"address"`
	Lat       *float64   `json:"lat"`
	Lng       *float64   `json:"lng"`
	CreatedBy *uuid.UUID `json:"created_by"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (BranchBranch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i BranchBranch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CreatedBy,
		&i.Region,
	)
	return i, err
}

const getAllBranches = `-- name: GetAllBranches :many
SELECT id, name, address, lat, lng, status, created_at, deleted_at, updated_at, updated_by, created_by, region FROM branch.branches
WHERE deleted_at IS NULL
`

func (q *Queries) GetAllBranches(ctx context.Context) ([]BranchBranch, error) {
	rows, err := q.db.Query(ctx, getAllBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchBranch{}
	for rows.Next() {
		var i BranchBranch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.CreatedBy,
			&i.Region,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, name, address, lat, lng, status, created_at, deleted_at, updated_at, updated_by, created_by, region FROM branch.branches
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetBranchByID(ctx context.Context, id uuid.UUID) (BranchBranch, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i BranchBranch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CreatedBy,
		&i.Region,
	)
	return i, err
}

const softDeleteBranch = `-- name: SoftDeleteBranch :exec
UPDATE branch.branches
SET deleted_at = NOW(), updated_by = $1
WHERE id = $2
`

type SoftDeleteBranchParams struct {
	UpdatedBy *uuid.UUID `json:"updated_by"`
	ID        uuid.UUID  `json:"id"`
}

func (q *Queries) SoftDeleteBranch(ctx context.Context, arg SoftDeleteBranchParams) error {
	_, err := q.db.Exec(ctx, softDeleteBranch, arg.UpdatedBy, arg.ID)
	return err
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branch.branches
SET
    name = $1,
    address = $2,
    lat = $3,
    lng = $4,
    updated_by = $5
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, name, address, lat, lng, status, created_at, deleted_at, updated_at, updated_by, created_by, region
`

type UpdateBranchParams struct {
	Name      string     `json:"name"`
	Address   string     `json:"address"`
	Lat       *float64   `json:"lat"`
	Lng       *float64   `json:"lng"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	ID        uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (BranchBranch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.UpdatedBy,
		arg.ID,
	)
	var i BranchBranch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.CreatedBy,
		&i.Region,
	)
	return i, err
}

const updateBranchStatus = `-- name: UpdateBranchStatus :exec
UPDATE branch.branches
SET status = $1, updated_by = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateBranchStatusParams struct {
	Status    string     `json:"status"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	ID        uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateBranchStatus(ctx context.Context, arg UpdateBranchStatusParams) error {
	_, err := q.db.Exec(ctx, updateBranchStatus, arg.Status, arg.UpdatedBy, arg.ID)
	return err
}
