// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_memberships.sql

package branchdb

import (
	"context"

	"github.com/google/uuid"
)

const countUsersByBranch = `-- name: CountUsersByBranch :one
SELECT COUNT(*) FROM branch.branch_memberships
WHERE branch_id = $1
`

func (q *Queries) CountUsersByBranch(ctx context.Context, branchID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByBranch, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBranchMembership = `-- name: DeleteBranchMembership :exec
DELETE FROM branch.branch_memberships
WHERE user_id = $1
`

func (q *Queries) DeleteBranchMembership(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBranchMembership, userID)
	return err
}

const getBranchMembership = `-- name: GetBranchMembership :one
SELECT id, user_id, branch_id, created_at, updated_at FROM branch.branch_memberships
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetBranchMembership(ctx context.Context, userID uuid.UUID) (BranchBranchMembership, error) {
	row := q.db.QueryRow(ctx, getBranchMembership, userID)
	var i BranchBranchMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByBranch = `-- name: ListUsersByBranch :many
SELECT user_id FROM branch.branch_memberships
WHERE branch_id = $1
`

func (q *Queries) ListUsersByBranch(ctx context.Context, branchID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUsersByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBranchMembership = `-- name: UpsertBranchMembership :one
INSERT INTO branch.branch_memberships (user_id, branch_id)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET branch_id = EXCLUDED.branch_id,
    updated_at = NOW()
RETURNING id, user_id, branch_id, created_at, updated_at
`

type UpsertBranchMembershipParams struct {
	UserID   uuid.UUID `json:"user_id"`
	BranchID uuid.UUID `json:"branch_id"`
}

func (q *Queries) UpsertBranchMembership(ctx context.Context, arg UpsertBranchMembershipParams) (BranchBranchMembership, error) {
	row := q.db.QueryRow(ctx, upsertBranchMembership, arg.UserID, arg.BranchID)
	var i BranchBranchMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BranchID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
