// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branches.sql

package branchdb

import (
	"context"

	"github.com/google/uuid"
)

const createBranch = `-- name: CreateBranch :one
INSERT INTO branch.branches (
    name, address, lat, lng
) VALUES ($1, $2, $3, $4)
    RETURNING id, name, address, lat, lng, status, created_at
`

type CreateBranchParams struct {
	Name    string   `json:"name"`
	Address string   `json:"address"`
	Lat     *float64 `json:"lat"`
	Lng     *float64 `json:"lng"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (BranchBranch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
	)
	var i BranchBranch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAllBranches = `-- name: GetAllBranches :many
SELECT id, name, address, lat, lng, status, created_at FROM branch.branches
`

func (q *Queries) GetAllBranches(ctx context.Context) ([]BranchBranch, error) {
	rows, err := q.db.Query(ctx, getAllBranches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BranchBranch{}
	for rows.Next() {
		var i BranchBranch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, name, address, lat, lng, status, created_at FROM branch.branches
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBranchByID(ctx context.Context, id uuid.UUID) (BranchBranch, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i BranchBranch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branch.branches
SET
    name = $1,
    address = $2,
    lat = $3,
    lng = $4
WHERE id = $5
RETURNING id, name, address, lat, lng, status, created_at
`

type UpdateBranchParams struct {
	Name    string    `json:"name"`
	Address string    `json:"address"`
	Lat     *float64  `json:"lat"`
	Lng     *float64  `json:"lng"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (BranchBranch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
		arg.ID,
	)
	var i BranchBranch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateBranchStatus = `-- name: UpdateBranchStatus :exec
UPDATE branch.branches
SET status = $1
WHERE id = $2
`

type UpdateBranchStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateBranchStatus(ctx context.Context, arg UpdateBranchStatusParams) error {
	_, err := q.db.Exec(ctx, updateBranchStatus, arg.Status, arg.ID)
	return err
}
