// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package branchdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type AuthAuthCredential struct {
	ID                uuid.UUID  `json:"id"`
	UserID            uuid.UUID  `json:"user_id"`
	PasswordHash      string     `json:"password_hash"`
	PasswordChangedAt time.Time  `json:"password_changed_at"`
	CreatedAt         time.Time  `json:"created_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
	CreatedBy         *uuid.UUID `json:"created_by"`
	UpdatedBy         *uuid.UUID `json:"updated_by"`
}

type AuthOutbox struct {
	ID          uuid.UUID  `json:"id"`
	RoutingKey  string     `json:"routing_key"`
	Payload     []byte     `json:"payload"`
	CreatedAt   time.Time  `json:"created_at"`
	PublishedAt *time.Time `json:"published_at"`
}

type AuthPermission struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type AuthRole struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

type AuthRolePermission struct {
	ID           uuid.UUID `json:"id"`
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type AuthUser struct {
	ID            uuid.UUID  `json:"id"`
	Email         string     `json:"email"`
	EmailVerified bool       `json:"email_verified"`
	IsActive      bool       `json:"is_active"`
	DeletedAt     *time.Time `json:"deleted_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	BranchID      *uuid.UUID `json:"branch_id"`
	CreatedBy     *uuid.UUID `json:"created_by"`
	UpdatedBy     *uuid.UUID `json:"updated_by"`
}

type AuthUserRole struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

type BranchBranch struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Address   string     `json:"address"`
	Lat       *float64   `json:"lat"`
	Lng       *float64   `json:"lng"`
	Status    string     `json:"status"`
	CreatedAt time.Time  `json:"created_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	CreatedBy *uuid.UUID `json:"created_by"`
	Region    string     `json:"region"`
}

type ProcurementOutbox struct {
	ID          uuid.UUID  `json:"id"`
	RoutingKey  string     `json:"routing_key"`
	Payload     []byte     `json:"payload"`
	PublishedAt *time.Time `json:"published_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type ProcurementPoItem struct {
	ID         uuid.UUID       `json:"id"`
	PoID       uuid.UUID       `json:"po_id"`
	ProductID  uuid.UUID       `json:"product_id"`
	Quantity   decimal.Decimal `json:"quantity"`
	UnitPrice  decimal.Decimal `json:"unit_price"`
	TotalPrice decimal.Decimal `json:"total_price"`
}

type ProcurementPurchaseOrder struct {
	ID          uuid.UUID       `json:"id"`
	SupplierID  uuid.UUID       `json:"supplier_id"`
	BranchID    uuid.UUID       `json:"branch_id"`
	Status      string          `json:"status"`
	TotalAmount decimal.Decimal `json:"total_amount"`
	Note        *string         `json:"note"`
	DeletedAt   *time.Time      `json:"deleted_at"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
	Version     int32           `json:"version"`
}

type ProcurementSupplier struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	ContactInfo *string    `json:"contact_info"`
	Region      string     `json:"region"`
	IsActive    bool       `json:"is_active"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

type ProductCategory struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	ParentID  *uuid.UUID `json:"parent_id"`
	SortOrder int32      `json:"sort_order"`
	IsActive  bool       `json:"is_active"`
	DeletedAt *time.Time `json:"deleted_at"`
	CreatedAt time.Time  `json:"created_at"`
	CreatedBy *uuid.UUID `json:"created_by"`
	UpdatedAt time.Time  `json:"updated_at"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

type ProductProduct struct {
	ID          uuid.UUID       `json:"id"`
	Sku         string          `json:"sku"`
	Name        string          `json:"name"`
	Slug        string          `json:"slug"`
	Description *string         `json:"description"`
	CategoryID  *uuid.UUID      `json:"category_id"`
	Unit        string          `json:"unit"`
	IsActive    bool            `json:"is_active"`
	DeletedAt   *time.Time      `json:"deleted_at"`
	CreatedAt   time.Time       `json:"created_at"`
	CreatedBy   *uuid.UUID      `json:"created_by"`
	UpdatedAt   time.Time       `json:"updated_at"`
	UpdatedBy   *uuid.UUID      `json:"updated_by"`
	BasePrice   decimal.Decimal `json:"base_price"`
}

type ProductProductImage struct {
	ID        uuid.UUID  `json:"id"`
	ProductID uuid.UUID  `json:"product_id"`
	Url       string     `json:"url"`
	IsPrimary bool       `json:"is_primary"`
	SortOrder int32      `json:"sort_order"`
	CreatedAt time.Time  `json:"created_at"`
	CreatedBy *uuid.UUID `json:"created_by"`
}

type ProductProductPrice struct {
	ID        uuid.UUID       `json:"id"`
	ProductID uuid.UUID       `json:"product_id"`
	BranchID  uuid.UUID       `json:"branch_id"`
	Price     decimal.Decimal `json:"price"`
	IsActive  bool            `json:"is_active"`
	DeletedAt *time.Time      `json:"deleted_at"`
	CreatedAt time.Time       `json:"created_at"`
	CreatedBy *uuid.UUID      `json:"created_by"`
	UpdatedAt time.Time       `json:"updated_at"`
	UpdatedBy *uuid.UUID      `json:"updated_by"`
}

type ProductProductPriceHistory struct {
	ID          uuid.UUID       `json:"id"`
	ProductID   uuid.UUID       `json:"product_id"`
	BranchID    *uuid.UUID      `json:"branch_id"`
	Price       decimal.Decimal `json:"price"`
	EffectiveAt time.Time       `json:"effective_at"`
	ChangedBy   *uuid.UUID      `json:"changed_by"`
}

type SharedProcessedEvent struct {
	EventID     uuid.UUID `json:"event_id"`
	Consumer    string    `json:"consumer"`
	ProcessedAt time.Time `json:"processed_at"`
}

type UsersProfile struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	AvatarUrl   *string   `json:"avatar_url"`
	Bio         *string   `json:"bio"`
	UpdatedAt   time.Time `json:"updated_at"`
}
