version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bakerio-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bakerio_network
    restart: unless-stopped

  migrate:
    image: migrate/migrate:v4.17.0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${PWD}/../db/migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      - -verbose
      - up
    networks:
      - bakerio_network
    restart: on-failure

  # redis:
  #   image: redis:7-alpine
  #   container_name: bakerio-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - bakerio_network
  #   restart: unless-stopped

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: bakerio-app
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      # redis:
      #   condition: service_healthy
    environment:
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      GIN_MODE: release
      JWT_EXPIRY: ${JWT_EXPIRY}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: disable
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - bakerio_network
    restart: unless-stopped

volumes:
  postgres_data:
  # redis_data:

networks:
  bakerio_network:
    driver: bridge
