// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ordersdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type AuthAuthCredential struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	PasswordHash      string    `json:"password_hash"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type AuthPermission struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type AuthRole struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

type AuthRolePermission struct {
	ID           uuid.UUID `json:"id"`
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type AuthUser struct {
	ID            uuid.UUID  `json:"id"`
	Email         string     `json:"email"`
	EmailVerified bool       `json:"email_verified"`
	IsActive      bool       `json:"is_active"`
	DeletedAt     *time.Time `json:"deleted_at"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

type AuthUserRole struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

type BranchBranch struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Address   string    `json:"address"`
	Lat       *float64  `json:"lat"`
	Lng       *float64  `json:"lng"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type BranchBranchMembership struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	BranchID  uuid.UUID `json:"branch_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CartCart struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type CartCartItem struct {
	ID            uuid.UUID       `json:"id"`
	CartID        uuid.UUID       `json:"cart_id"`
	ProductID     uuid.UUID       `json:"product_id"`
	Quantity      int32           `json:"quantity"`
	UnitPriceSnap decimal.Decimal `json:"unit_price_snap"`
	AddedAt       time.Time       `json:"added_at"`
}

type NotificationUserNotification struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Type      string     `json:"type"`
	Title     string     `json:"title"`
	Body      string     `json:"body"`
	Data      []byte     `json:"data"`
	ReadAt    *time.Time `json:"read_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type OrdersOrder struct {
	ID                uuid.UUID       `json:"id"`
	Code              string          `json:"code"`
	UserID            uuid.UUID       `json:"user_id"`
	BranchID          uuid.UUID       `json:"branch_id"`
	Subtotal          decimal.Decimal `json:"subtotal"`
	DiscountTotal     decimal.Decimal `json:"discount_total"`
	ShippingFee       decimal.Decimal `json:"shipping_fee"`
	Total             decimal.Decimal `json:"total"`
	ShippingAddress   string          `json:"shipping_address"`
	ShippingLatitude  *float64        `json:"shipping_latitude"`
	ShippingLongitude *float64        `json:"shipping_longitude"`
	ContactPhone      *string         `json:"contact_phone"`
	Note              *string         `json:"note"`
	RoutingReason     *string         `json:"routing_reason"`
	PlacedAt          time.Time       `json:"placed_at"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type OrdersOrderItem struct {
	ID            uuid.UUID       `json:"id"`
	OrderID       uuid.UUID       `json:"order_id"`
	ProductID     uuid.UUID       `json:"product_id"`
	NameSnap      string          `json:"name_snap"`
	UnitPriceSnap decimal.Decimal `json:"unit_price_snap"`
	Quantity      int32           `json:"quantity"`
	LineTotal     decimal.Decimal `json:"line_total"`
}

type OutboxEvent struct {
	ID          uuid.UUID  `json:"id"`
	RoutingKey  string     `json:"routing_key"`
	Payload     []byte     `json:"payload"`
	CreatedAt   time.Time  `json:"created_at"`
	PublishedAt *time.Time `json:"published_at"`
}

type ProductBranchProduct struct {
	ID        uuid.UUID  `json:"id"`
	ProductID uuid.UUID  `json:"product_id"`
	BranchID  uuid.UUID  `json:"branch_id"`
	IsActive  bool       `json:"is_active"`
	CreatedAt time.Time  `json:"created_at"`
	CreatedBy *uuid.UUID `json:"created_by"`
	UpdatedAt time.Time  `json:"updated_at"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
	Quantity  int32      `json:"quantity"`
}

type ProductCategory struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	SortOrder int32      `json:"sort_order"`
	IsActive  bool       `json:"is_active"`
	DeletedAt *time.Time `json:"deleted_at"`
	CreatedAt time.Time  `json:"created_at"`
	CreatedBy *uuid.UUID `json:"created_by"`
	UpdatedAt time.Time  `json:"updated_at"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

type ProductProduct struct {
	ID         uuid.UUID       `json:"id"`
	Name       string          `json:"name"`
	Slug       string          `json:"slug"`
	CategoryID uuid.UUID       `json:"category_id"`
	Price      decimal.Decimal `json:"price"`
	SortOrder  int32           `json:"sort_order"`
	IsActive   bool            `json:"is_active"`
	DeletedAt  *time.Time      `json:"deleted_at"`
	CreatedAt  time.Time       `json:"created_at"`
	CreatedBy  *uuid.UUID      `json:"created_by"`
	UpdatedAt  time.Time       `json:"updated_at"`
	UpdatedBy  *uuid.UUID      `json:"updated_by"`
}

type ProductProductImage struct {
	ID        uuid.UUID  `json:"id"`
	ProductID uuid.UUID  `json:"product_id"`
	ImageUrl  string     `json:"image_url"`
	AltText   *string    `json:"alt_text"`
	SortOrder int32      `json:"sort_order"`
	CreatedAt time.Time  `json:"created_at"`
	CreatedBy *uuid.UUID `json:"created_by"`
	UpdatedAt time.Time  `json:"updated_at"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

type UsersAddress struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Address   string    `json:"address"`
	Latitude  float64   `json:"latitude"`
	Longitude float64   `json:"longitude"`
	IsDefault bool      `json:"is_default"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UsersMembership struct {
	UserID     uuid.UUID       `json:"user_id"`
	Tier       string          `json:"tier"`
	TotalSpent decimal.Decimal `json:"total_spent"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type UsersProfile struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	DisplayName string    `json:"display_name"`
	Phone       *string   `json:"phone"`
	AvatarUrl   *string   `json:"avatar_url"`
	Bio         *string   `json:"bio"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type VoucherRedemption struct {
	ID             uuid.UUID       `json:"id"`
	VoucherID      uuid.UUID       `json:"voucher_id"`
	UserID         uuid.UUID       `json:"user_id"`
	OrderID        uuid.UUID       `json:"order_id"`
	DiscountAmount decimal.Decimal `json:"discount_amount"`
	RedeemedAt     time.Time       `json:"redeemed_at"`
}

type VoucherVoucher struct {
	ID              uuid.UUID        `json:"id"`
	Code            string           `json:"code"`
	DiscountPercent int16            `json:"discount_percent"`
	MaxDiscount     *decimal.Decimal `json:"max_discount"`
	MinSubtotal     *decimal.Decimal `json:"min_subtotal"`
	ValidFrom       time.Time        `json:"valid_from"`
	ValidTo         time.Time        `json:"valid_to"`
	IsActive        bool             `json:"is_active"`
	CreatedAt       time.Time        `json:"created_at"`
	CreatedBy       *uuid.UUID       `json:"created_by"`
	UpdatedAt       time.Time        `json:"updated_at"`
	UpdatedBy       *uuid.UUID       `json:"updated_by"`
}
