// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_products.sql

package productdb

import (
	"context"

	"github.com/google/uuid"
)

const fanoutProductToBranches = `-- name: FanoutProductToBranches :exec
INSERT INTO product.branch_products (product_id, branch_id, created_by, updated_by)
SELECT $1, b, $3, $3
FROM unnest($2::uuid[]) AS b
ON CONFLICT (product_id, branch_id) DO NOTHING
`

type FanoutProductToBranchesParams struct {
	ProductID uuid.UUID   `json:"product_id"`
	Column2   []uuid.UUID `json:"column_2"`
	CreatedBy *uuid.UUID  `json:"created_by"`
}

// On product create: insert one row per branch, inactive (opt-in).
func (q *Queries) FanoutProductToBranches(ctx context.Context, arg FanoutProductToBranchesParams) error {
	_, err := q.db.Exec(ctx, fanoutProductToBranches, arg.ProductID, arg.Column2, arg.CreatedBy)
	return err
}

const getBranchProduct = `-- name: GetBranchProduct :one
SELECT id, product_id, branch_id, is_active, created_at, created_by, updated_at, updated_by FROM product.branch_products
WHERE product_id = $1 AND branch_id = $2
`

type GetBranchProductParams struct {
	ProductID uuid.UUID `json:"product_id"`
	BranchID  uuid.UUID `json:"branch_id"`
}

func (q *Queries) GetBranchProduct(ctx context.Context, arg GetBranchProductParams) (ProductBranchProduct, error) {
	row := q.db.QueryRow(ctx, getBranchProduct, arg.ProductID, arg.BranchID)
	var i ProductBranchProduct
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listActiveProductsByBranch = `-- name: ListActiveProductsByBranch :many
SELECT p.id, p.name, p.slug, p.category_id, p.price, p.sort_order, p.is_active, p.deleted_at, p.created_at, p.created_by, p.updated_at, p.updated_by FROM product.products p
JOIN product.branch_products bp ON bp.product_id = p.id
WHERE bp.branch_id = $1
  AND bp.is_active = TRUE
  AND p.is_active = TRUE
  AND p.deleted_at IS NULL
ORDER BY p.sort_order ASC, p.name ASC
`

// Customer-facing: products sellable at a branch (both flags true).
func (q *Queries) ListActiveProductsByBranch(ctx context.Context, branchID uuid.UUID) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, listActiveProductsByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CategoryID,
			&i.Price,
			&i.SortOrder,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchProductsByBranch = `-- name: ListBranchProductsByBranch :many
SELECT id, product_id, branch_id, is_active, created_at, created_by, updated_at, updated_by FROM product.branch_products
WHERE branch_id = $1
`

// Admin/manager matrix view: every product's availability at a branch.
func (q *Queries) ListBranchProductsByBranch(ctx context.Context, branchID uuid.UUID) ([]ProductBranchProduct, error) {
	rows, err := q.db.Query(ctx, listBranchProductsByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductBranchProduct{}
	for rows.Next() {
		var i ProductBranchProduct
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BranchID,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedBranchProducts = `-- name: SeedBranchProducts :exec
INSERT INTO product.branch_products (product_id, branch_id, created_by, updated_by)
SELECT p.id, $1, $2, $2
FROM product.products p
WHERE p.deleted_at IS NULL
ON CONFLICT (product_id, branch_id) DO NOTHING
`

type SeedBranchProductsParams struct {
	BranchID  uuid.UUID  `json:"branch_id"`
	CreatedBy *uuid.UUID `json:"created_by"`
}

// On branch create: insert a row for every existing product, inactive (opt-in).
func (q *Queries) SeedBranchProducts(ctx context.Context, arg SeedBranchProductsParams) error {
	_, err := q.db.Exec(ctx, seedBranchProducts, arg.BranchID, arg.CreatedBy)
	return err
}

const setBranchProductActive = `-- name: SetBranchProductActive :one
UPDATE product.branch_products
SET is_active  = $3,
    updated_at = NOW(),
    updated_by = $4
WHERE product_id = $1 AND branch_id = $2
RETURNING id, product_id, branch_id, is_active, created_at, created_by, updated_at, updated_by
`

type SetBranchProductActiveParams struct {
	ProductID uuid.UUID  `json:"product_id"`
	BranchID  uuid.UUID  `json:"branch_id"`
	IsActive  bool       `json:"is_active"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SetBranchProductActive(ctx context.Context, arg SetBranchProductActiveParams) (ProductBranchProduct, error) {
	row := q.db.QueryRow(ctx, setBranchProductActive,
		arg.ProductID,
		arg.BranchID,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i ProductBranchProduct
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
