// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: branch_products.sql

package productdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const decrementBranchStock = `-- name: DecrementBranchStock :execrows
UPDATE product.branch_products
SET quantity   = quantity - $3,
    updated_at = NOW()
WHERE branch_id = $1
  AND product_id = $2
  AND quantity >= $3
  AND is_active = TRUE
`

type DecrementBranchStockParams struct {
	BranchID  uuid.UUID `json:"branch_id"`
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
}

// Atomic subtract — fires only when current stock is enough AND the row is
// still active. Returns rows-affected (1 = success, 0 = lost the race or
// product deactivated). Service uses the count to detect failure and roll
// back the entire tx.
func (q *Queries) DecrementBranchStock(ctx context.Context, arg DecrementBranchStockParams) (int64, error) {
	result, err := q.db.Exec(ctx, decrementBranchStock, arg.BranchID, arg.ProductID, arg.Quantity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fanoutProductToBranches = `-- name: FanoutProductToBranches :exec
INSERT INTO product.branch_products (product_id, branch_id, created_by, updated_by)
SELECT $1, b, $3, $3
FROM unnest($2::uuid[]) AS b
ON CONFLICT (product_id, branch_id) DO NOTHING
`

type FanoutProductToBranchesParams struct {
	ProductID uuid.UUID   `json:"product_id"`
	Column2   []uuid.UUID `json:"column_2"`
	CreatedBy *uuid.UUID  `json:"created_by"`
}

// On product create: insert one row per branch, inactive (opt-in).
func (q *Queries) FanoutProductToBranches(ctx context.Context, arg FanoutProductToBranchesParams) error {
	_, err := q.db.Exec(ctx, fanoutProductToBranches, arg.ProductID, arg.Column2, arg.CreatedBy)
	return err
}

const getBranchProduct = `-- name: GetBranchProduct :one
SELECT id, product_id, branch_id, is_active, created_at, created_by, updated_at, updated_by, quantity FROM product.branch_products
WHERE product_id = $1 AND branch_id = $2
`

type GetBranchProductParams struct {
	ProductID uuid.UUID `json:"product_id"`
	BranchID  uuid.UUID `json:"branch_id"`
}

func (q *Queries) GetBranchProduct(ctx context.Context, arg GetBranchProductParams) (ProductBranchProduct, error) {
	row := q.db.QueryRow(ctx, getBranchProduct, arg.ProductID, arg.BranchID)
	var i ProductBranchProduct
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Quantity,
	)
	return i, err
}

const getProductsByIDs = `-- name: GetProductsByIDs :many
SELECT id, name, price
FROM product.products
WHERE id = ANY($1::uuid[])
  AND is_active = TRUE
  AND deleted_at IS NULL
`

type GetProductsByIDsRow struct {
	ID    uuid.UUID       `json:"id"`
	Name  string          `json:"name"`
	Price decimal.Decimal `json:"price"`
}

// Pulls live name + price for snapshotting onto the order session at
// /orders/select-branch. Filters to active + undeleted; client must
// handle a missing product as "stale catalog, refresh".
func (q *Queries) GetProductsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetProductsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProductsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductsByIDsRow{}
	for rows.Next() {
		var i GetProductsByIDsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProductsByBranch = `-- name: ListActiveProductsByBranch :many
SELECT p.id, p.name, p.slug, p.category_id, p.price, p.sort_order, p.is_active, p.deleted_at, p.created_at, p.created_by, p.updated_at, p.updated_by FROM product.products p
JOIN product.branch_products bp ON bp.product_id = p.id
WHERE bp.branch_id = $1
  AND bp.is_active = TRUE
  AND p.is_active = TRUE
  AND p.deleted_at IS NULL
ORDER BY p.sort_order ASC, p.name ASC
`

// Customer-facing: products sellable at a branch (both flags true).
func (q *Queries) ListActiveProductsByBranch(ctx context.Context, branchID uuid.UUID) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, listActiveProductsByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CategoryID,
			&i.Price,
			&i.SortOrder,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchProductsByBranch = `-- name: ListBranchProductsByBranch :many
SELECT id, product_id, branch_id, is_active, created_at, created_by, updated_at, updated_by, quantity FROM product.branch_products
WHERE branch_id = $1
`

// Admin/manager matrix view: every product's availability at a branch.
func (q *Queries) ListBranchProductsByBranch(ctx context.Context, branchID uuid.UUID) ([]ProductBranchProduct, error) {
	rows, err := q.db.Query(ctx, listBranchProductsByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductBranchProduct{}
	for rows.Next() {
		var i ProductBranchProduct
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BranchID,
			&i.IsActive,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBranchProductsForManage = `-- name: ListBranchProductsForManage :many
SELECT bp.product_id,
       bp.branch_id,
       bp.is_active,
       bp.quantity,
       p.name,
       p.slug,
       p.price,
       p.is_active AS product_active
FROM product.branch_products bp
JOIN product.products p ON p.id = bp.product_id
WHERE bp.branch_id = $1
  AND p.deleted_at IS NULL
  AND (NOT $2::boolean OR bp.is_active = $3::boolean)
ORDER BY p.sort_order ASC, p.name ASC
`

type ListBranchProductsForManageParams struct {
	BranchID     uuid.UUID `json:"branch_id"`
	FilterActive bool      `json:"filter_active"`
	IsActive     bool      `json:"is_active"`
}

type ListBranchProductsForManageRow struct {
	ProductID     uuid.UUID       `json:"product_id"`
	BranchID      uuid.UUID       `json:"branch_id"`
	IsActive      bool            `json:"is_active"`
	Quantity      int32           `json:"quantity"`
	Name          string          `json:"name"`
	Slug          string          `json:"slug"`
	Price         decimal.Decimal `json:"price"`
	ProductActive bool            `json:"product_active"`
}

// Admin/manager matrix view enriched with product details. The boolean
// "filter_active" flag picks whether to filter by is_active; when false,
// all rows are returned regardless of the "is_active" argument.
func (q *Queries) ListBranchProductsForManage(ctx context.Context, arg ListBranchProductsForManageParams) ([]ListBranchProductsForManageRow, error) {
	rows, err := q.db.Query(ctx, listBranchProductsForManage, arg.BranchID, arg.FilterActive, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchProductsForManageRow{}
	for rows.Next() {
		var i ListBranchProductsForManageRow
		if err := rows.Scan(
			&i.ProductID,
			&i.BranchID,
			&i.IsActive,
			&i.Quantity,
			&i.Name,
			&i.Slug,
			&i.Price,
			&i.ProductActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readBranchStock = `-- name: ReadBranchStock :many
SELECT product_id, quantity, is_active
FROM product.branch_products
WHERE branch_id = $1 AND product_id = ANY($2::uuid[])
`

type ReadBranchStockParams struct {
	BranchID uuid.UUID   `json:"branch_id"`
	Column2  []uuid.UUID `json:"column_2"`
}

type ReadBranchStockRow struct {
	ProductID uuid.UUID `json:"product_id"`
	Quantity  int32     `json:"quantity"`
	IsActive  bool      `json:"is_active"`
}

// Non-locking pre-check used by order/confirm to build a rich
// STOCK_CONFLICT payload (report all problematic items at once instead of
// one-at-a-time across retries). The atomic UPDATE in DecrementBranchStock
// is what actually enforces the invariant — this SELECT is informational.
func (q *Queries) ReadBranchStock(ctx context.Context, arg ReadBranchStockParams) ([]ReadBranchStockRow, error) {
	rows, err := q.db.Query(ctx, readBranchStock, arg.BranchID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadBranchStockRow{}
	for rows.Next() {
		var i ReadBranchStockRow
		if err := rows.Scan(&i.ProductID, &i.Quantity, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedBranchProducts = `-- name: SeedBranchProducts :exec
INSERT INTO product.branch_products (product_id, branch_id, created_by, updated_by)
SELECT p.id, $1, $2, $2
FROM product.products p
WHERE p.deleted_at IS NULL
ON CONFLICT (product_id, branch_id) DO NOTHING
`

type SeedBranchProductsParams struct {
	BranchID  uuid.UUID  `json:"branch_id"`
	CreatedBy *uuid.UUID `json:"created_by"`
}

// On branch create: insert a row for every existing product, inactive (opt-in).
func (q *Queries) SeedBranchProducts(ctx context.Context, arg SeedBranchProductsParams) error {
	_, err := q.db.Exec(ctx, seedBranchProducts, arg.BranchID, arg.CreatedBy)
	return err
}

const updateBranchProduct = `-- name: UpdateBranchProduct :one
UPDATE product.branch_products
SET is_active  = CASE WHEN $3::boolean
                      THEN $4::boolean
                      ELSE is_active END,
    quantity   = CASE WHEN $5::boolean
                      THEN $6::int4
                      ELSE quantity END,
    updated_at = NOW(),
    updated_by = $7
WHERE product_id = $1 AND branch_id = $2
RETURNING id, product_id, branch_id, is_active, created_at, created_by, updated_at, updated_by, quantity
`

type UpdateBranchProductParams struct {
	ProductID   uuid.UUID  `json:"product_id"`
	BranchID    uuid.UUID  `json:"branch_id"`
	SetActive   bool       `json:"set_active"`
	IsActive    bool       `json:"is_active"`
	SetQuantity bool       `json:"set_quantity"`
	Quantity    int32      `json:"quantity"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

// Patch availability and/or quantity at a branch. The boolean "set_*" flags
// pick whether the corresponding column is overwritten or left as-is, so the
// same endpoint covers toggle-only, set-stock-only, or both at once.
func (q *Queries) UpdateBranchProduct(ctx context.Context, arg UpdateBranchProductParams) (ProductBranchProduct, error) {
	row := q.db.QueryRow(ctx, updateBranchProduct,
		arg.ProductID,
		arg.BranchID,
		arg.SetActive,
		arg.IsActive,
		arg.SetQuantity,
		arg.Quantity,
		arg.UpdatedBy,
	)
	var i ProductBranchProduct
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.IsActive,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Quantity,
	)
	return i, err
}
