// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package productdb

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO product.categories (
    name, slug, parent_id, sort_order, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, slug, parent_id, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by
`

type CreateCategoryParams struct {
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	ParentID  *uuid.UUID `json:"parent_id"`
	SortOrder int32      `json:"sort_order"`
	CreatedBy *uuid.UUID `json:"created_by"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.SortOrder,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, parent_id, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.categories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, parent_id, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.categories
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, parent_id, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.categories
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]ProductCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductCategory{}
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.SortOrder,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE product.categories
SET 
    deleted_at = NOW(),
    updated_by = $2
WHERE id = $1
`

type SoftDeleteCategoryParams struct {
	ID        uuid.UUID  `json:"id"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, arg.ID, arg.UpdatedBy)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE product.categories
SET 
    name = $2,
    slug = $3,
    parent_id = $4,
    sort_order = $5,
    is_active = $6,
    updated_at = NOW(),
    updated_by = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, parent_id, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by
`

type UpdateCategoryParams struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	ParentID  *uuid.UUID `json:"parent_id"`
	SortOrder int32      `json:"sort_order"`
	IsActive  bool       `json:"is_active"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.SortOrder,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
