// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package productdb

import (
	"context"

	"github.com/google/uuid"
)

const addProductImage = `-- name: AddProductImage :one
INSERT INTO product.product_images (
    product_id, url, is_primary, sort_order, created_by
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, product_id, url, is_primary, sort_order, created_at, created_by
`

type AddProductImageParams struct {
	ProductID uuid.UUID  `json:"product_id"`
	Url       string     `json:"url"`
	IsPrimary bool       `json:"is_primary"`
	SortOrder int32      `json:"sort_order"`
	CreatedBy *uuid.UUID `json:"created_by"`
}

func (q *Queries) AddProductImage(ctx context.Context, arg AddProductImageParams) (ProductProductImage, error) {
	row := q.db.QueryRow(ctx, addProductImage,
		arg.ProductID,
		arg.Url,
		arg.IsPrimary,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i ProductProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const clearPrimaryImage = `-- name: ClearPrimaryImage :exec
UPDATE product.product_images
SET is_primary = false
WHERE product_id = $1
`

func (q *Queries) ClearPrimaryImage(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPrimaryImage, productID)
	return err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product.product_images
WHERE id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImage, id)
	return err
}

const getProductImageByID = `-- name: GetProductImageByID :one
SELECT id, product_id, url, is_primary, sort_order, created_at, created_by FROM product.product_images
WHERE id = $1
`

func (q *Queries) GetProductImageByID(ctx context.Context, id uuid.UUID) (ProductProductImage, error) {
	row := q.db.QueryRow(ctx, getProductImageByID, id)
	var i ProductProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.IsPrimary,
		&i.SortOrder,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, url, is_primary, sort_order, created_at, created_by FROM product.product_images
WHERE product_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListProductImages(ctx context.Context, productID uuid.UUID) ([]ProductProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProductImage{}
	for rows.Next() {
		var i ProductProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.IsPrimary,
			&i.SortOrder,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrimaryImage = `-- name: SetPrimaryImage :exec
UPDATE product.product_images
SET is_primary = true
WHERE id = $1
`

func (q *Queries) SetPrimaryImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPrimaryImage, id)
	return err
}
