// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_images.sql

package productdb

import (
	"context"

	"github.com/google/uuid"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product.product_images (
    product_id, image_url, alt_text, sort_order, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $5
) RETURNING id, product_id, image_url, alt_text, sort_order, created_at, created_by, updated_at, updated_by
`

type CreateProductImageParams struct {
	ProductID uuid.UUID  `json:"product_id"`
	ImageUrl  string     `json:"image_url"`
	AltText   *string    `json:"alt_text"`
	SortOrder int32      `json:"sort_order"`
	CreatedBy *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.ProductID,
		arg.ImageUrl,
		arg.AltText,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i ProductProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.AltText,
		&i.SortOrder,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product.product_images
WHERE id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductImage, id)
	return err
}

const listImagesByProduct = `-- name: ListImagesByProduct :many
SELECT id, product_id, image_url, alt_text, sort_order, created_at, created_by, updated_at, updated_by FROM product.product_images
WHERE product_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListImagesByProduct(ctx context.Context, productID uuid.UUID) ([]ProductProductImage, error) {
	rows, err := q.db.Query(ctx, listImagesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProductImage{}
	for rows.Next() {
		var i ProductProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImageUrl,
			&i.AltText,
			&i.SortOrder,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByProductIDs = `-- name: ListImagesByProductIDs :many
SELECT id, product_id, image_url, alt_text, sort_order, created_at, created_by, updated_at, updated_by FROM product.product_images
WHERE product_id = ANY($1::uuid[])
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListImagesByProductIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductProductImage, error) {
	rows, err := q.db.Query(ctx, listImagesByProductIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProductImage{}
	for rows.Next() {
		var i ProductProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImageUrl,
			&i.AltText,
			&i.SortOrder,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
