// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package productdb

import (
	"context"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product.products (
    sku, name, slug, description, category_id, unit, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, sku, name, slug, description, category_id, unit, is_active, deleted_at, created_at, created_by, updated_at, updated_by
`

type CreateProductParams struct {
	Sku         string     `json:"sku"`
	Name        string     `json:"name"`
	Slug        string     `json:"slug"`
	Description *string    `json:"description"`
	CategoryID  *uuid.UUID `json:"category_id"`
	Unit        string     `json:"unit"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CategoryID,
		arg.Unit,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CategoryID,
		&i.Unit,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, sku, name, slug, description, category_id, unit, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.products
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CategoryID,
		&i.Unit,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, sku, name, slug, description, category_id, unit, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.products
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CategoryID,
		&i.Unit,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, sku, name, slug, description, category_id, unit, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.products
WHERE deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListProducts(ctx context.Context) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CategoryID,
			&i.Unit,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, sku, name, slug, description, category_id, unit, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.products
WHERE category_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListProductsByCategory(ctx context.Context, categoryID *uuid.UUID) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CategoryID,
			&i.Unit,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE product.products
SET 
    deleted_at = NOW(),
    updated_by = $2
WHERE id = $1
`

type SoftDeleteProductParams struct {
	ID        uuid.UUID  `json:"id"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.UpdatedBy)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product.products
SET 
    sku = $2,
    name = $3,
    slug = $4,
    description = $5,
    category_id = $6,
    unit = $7,
    is_active = $8,
    updated_at = NOW(),
    updated_by = $9
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, sku, name, slug, description, category_id, unit, is_active, deleted_at, created_at, created_by, updated_at, updated_by
`

type UpdateProductParams struct {
	ID          uuid.UUID  `json:"id"`
	Sku         string     `json:"sku"`
	Name        string     `json:"name"`
	Slug        string     `json:"slug"`
	Description *string    `json:"description"`
	CategoryID  *uuid.UUID `json:"category_id"`
	Unit        string     `json:"unit"`
	IsActive    bool       `json:"is_active"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.CategoryID,
		arg.Unit,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CategoryID,
		&i.Unit,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
