// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package productdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM product.products
WHERE deleted_at IS NULL
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByCategory = `-- name: CountProductsByCategory :one
SELECT COUNT(*) FROM product.products
WHERE deleted_at IS NULL AND category_id = $1
`

func (q *Queries) CountProductsByCategory(ctx context.Context, categoryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByCategorySlug = `-- name: CountProductsByCategorySlug :one
SELECT COUNT(*) FROM product.products p
JOIN product.categories c ON p.category_id = c.id
WHERE p.deleted_at IS NULL AND c.slug = $1
`

func (q *Queries) CountProductsByCategorySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByCategorySlug, slug)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO product.products (
    name, slug, category_id, price, sort_order, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $6
) RETURNING id, name, slug, category_id, price, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by
`

type CreateProductParams struct {
	Name       string          `json:"name"`
	Slug       string          `json:"slug"`
	CategoryID uuid.UUID       `json:"category_id"`
	Price      decimal.Decimal `json:"price"`
	SortOrder  int32           `json:"sort_order"`
	CreatedBy  *uuid.UUID      `json:"created_by"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Slug,
		arg.CategoryID,
		arg.Price,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CategoryID,
		&i.Price,
		&i.SortOrder,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getActiveProductsByIDs = `-- name: GetActiveProductsByIDs :many
SELECT id, name, slug, category_id, price, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.products
WHERE id = ANY($1::uuid[]) AND is_active = TRUE AND deleted_at IS NULL
`

// For cart/order to validate and snapshot products.
func (q *Queries) GetActiveProductsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, getActiveProductsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CategoryID,
			&i.Price,
			&i.SortOrder,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, slug, category_id, price, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.products
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CategoryID,
		&i.Price,
		&i.SortOrder,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, slug, category_id, price, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.products
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CategoryID,
		&i.Price,
		&i.SortOrder,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, slug, category_id, price, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.products
WHERE deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CategoryID,
			&i.Price,
			&i.SortOrder,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, name, slug, category_id, price, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by FROM product.products
WHERE deleted_at IS NULL AND category_id = $1
ORDER BY sort_order ASC, name ASC
LIMIT $2 OFFSET $3
`

type ListProductsByCategoryParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CategoryID,
			&i.Price,
			&i.SortOrder,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategorySlug = `-- name: ListProductsByCategorySlug :many
SELECT p.id, p.name, p.slug, p.category_id, p.price, p.sort_order, p.is_active, p.deleted_at, p.created_at, p.created_by, p.updated_at, p.updated_by FROM product.products p
JOIN product.categories c ON p.category_id = c.id
WHERE p.deleted_at IS NULL AND c.slug = $1
ORDER BY p.sort_order ASC, p.name ASC
LIMIT $2 OFFSET $3
`

type ListProductsByCategorySlugParams struct {
	Slug   string `json:"slug"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListProductsByCategorySlug(ctx context.Context, arg ListProductsByCategorySlugParams) ([]ProductProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByCategorySlug, arg.Slug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductProduct{}
	for rows.Next() {
		var i ProductProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CategoryID,
			&i.Price,
			&i.SortOrder,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE product.products
SET deleted_at = NOW(),
    updated_by = $2
WHERE id = $1
`

type SoftDeleteProductParams struct {
	ID        uuid.UUID  `json:"id"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.UpdatedBy)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE product.products
SET
    name        = $2,
    slug        = $3,
    category_id = $4,
    price       = $5,
    sort_order  = $6,
    is_active   = $7,
    updated_at  = NOW(),
    updated_by  = $8
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, category_id, price, sort_order, is_active, deleted_at, created_at, created_by, updated_at, updated_by
`

type UpdateProductParams struct {
	ID         uuid.UUID       `json:"id"`
	Name       string          `json:"name"`
	Slug       string          `json:"slug"`
	CategoryID uuid.UUID       `json:"category_id"`
	Price      decimal.Decimal `json:"price"`
	SortOrder  int32           `json:"sort_order"`
	IsActive   bool            `json:"is_active"`
	UpdatedBy  *uuid.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (ProductProduct, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CategoryID,
		arg.Price,
		arg.SortOrder,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i ProductProduct
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CategoryID,
		&i.Price,
		&i.SortOrder,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
