package service

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/octguy/bakerio/backend/internal/platform/outbox"
	"github.com/octguy/bakerio/backend/internal/procurement/dto"
	"github.com/octguy/bakerio/backend/internal/procurement/repository"
	"github.com/octguy/bakerio/backend/internal/shared/apperrors"
	"github.com/octguy/bakerio/backend/internal/shared/authcontext"
	"github.com/octguy/bakerio/backend/internal/shared/domain"
	"github.com/octguy/bakerio/backend/pkg/txmanager"
	"github.com/shopspring/decimal"
)

type ProcurementService interface {
	CreatePO(ctx context.Context, req dto.CreatePORequest) (dto.POResponse, error)
	GetPO(ctx context.Context, id uuid.UUID) (dto.POResponse, error)
	ListPOs(ctx context.Context) ([]dto.POResponse, error)
	UpdateStatus(ctx context.Context, id uuid.UUID, newStatus string) (dto.POResponse, error)
}

type procurementService struct {
	repo      repository.ProcurementRepository
	supRepo   repository.SupplierRepository
	txManager txmanager.TransactionManager
	outbox    outbox.Source
}

func NewProcurementService(
	repo repository.ProcurementRepository,
	supRepo repository.SupplierRepository,
	txManager txmanager.TransactionManager,
	outbox outbox.Source,
) ProcurementService {
	return &procurementService{
		repo:      repo,
		supRepo:   supRepo,
		txManager: txManager,
		outbox:    outbox,
	}
}

func (s *procurementService) CreatePO(ctx context.Context, req dto.CreatePORequest) (dto.POResponse, error) {
	branchID, ok := authcontext.CallerBranchID(ctx)
	if !ok || branchID == uuid.Nil {
		return dto.POResponse{}, apperrors.Forbidden("no branch assigned to current user")
	}

	_, err := s.supRepo.GetByID(ctx, req.SupplierID)
	if err != nil {
		return dto.POResponse{}, apperrors.NotFound("supplier not found")
	}

	var createdPO *domain.PurchaseOrder
	err = s.txManager.WithTx(ctx, func(ctx context.Context) error {
		totalAmount := decimal.Zero
		items := make([]*domain.POItem, 0, len(req.Items))

		for _, itemReq := range req.Items {
			lineTotal := itemReq.Quantity.Mul(itemReq.UnitPrice)
			totalAmount = totalAmount.Add(lineTotal)
			items = append(items, &domain.POItem{
				ProductID: itemReq.ProductID,
				Quantity:  itemReq.Quantity,
				UnitPrice: itemReq.UnitPrice,
				// TotalPrice is generated by the DB (quantity * unit_price)
			})
		}

		po := &domain.PurchaseOrder{
			SupplierID:  req.SupplierID,
			BranchID:    branchID,
			Status:      domain.POStatusDraft,
			TotalAmount: totalAmount,
			Note:        &req.Note,
		}

		createdPO, err = s.repo.CreatePO(ctx, po)
		if err != nil {
			return fmt.Errorf("creating PO: %w", err)
		}

		for _, item := range items {
			item.POID = createdPO.ID
			createdItem, err := s.repo.CreatePOItem(ctx, item)
			if err != nil {
				return fmt.Errorf("creating PO item: %w", err)
			}
			createdPO.Items = append(createdPO.Items, createdItem)
		}

		return nil
	})

	if err != nil {
		return dto.POResponse{}, apperrors.Internal("transaction failed", err)
	}

	return toPOResponse(createdPO), nil
}

func (s *procurementService) GetPO(ctx context.Context, id uuid.UUID) (dto.POResponse, error) {
	po, err := s.repo.GetPO(ctx, id)
	if err != nil {
		return dto.POResponse{}, apperrors.NotFound("purchase order not found")
	}

	items, err := s.repo.GetPOItems(ctx, id)
	if err != nil {
		return dto.POResponse{}, apperrors.Internal("failed to fetch PO items", err)
	}
	po.Items = items

	return toPOResponse(po), nil
}

func (s *procurementService) ListPOs(ctx context.Context) ([]dto.POResponse, error) {
	branchID, ok := authcontext.CallerBranchID(ctx)
	if !ok || branchID == uuid.Nil {
		return nil, apperrors.Forbidden("no branch assigned")
	}

	pos, err := s.repo.ListPOsByBranch(ctx, branchID)
	if err != nil {
		return nil, apperrors.Internal("failed to list POs", err)
	}

	res := make([]dto.POResponse, 0, len(pos))
	for _, po := range pos {
		res = append(res, toPOResponse(po))
	}
	return res, nil
}

func (s *procurementService) UpdateStatus(ctx context.Context, id uuid.UUID, newStatus string) (dto.POResponse, error) {
	current, err := s.repo.GetPO(ctx, id)
	if err != nil {
		return dto.POResponse{}, apperrors.NotFound("purchase order not found")
	}

	if !isValidTransition(current.Status, newStatus) {
		return dto.POResponse{}, apperrors.Validation(fmt.Sprintf("invalid transition from %s to %s", current.Status, newStatus))
	}

	var updatedPO *domain.PurchaseOrder
	err = s.txManager.WithTx(ctx, func(ctx context.Context) error {
		updatedPO, err = s.repo.UpdatePOStatus(ctx, id, newStatus)
		if err != nil {
			return err
		}

		if newStatus == domain.POStatusReceived {
			// Fetch items for the event
			items, err := s.repo.GetPOItems(ctx, id)
			if err != nil {
				return err
			}
			updatedPO.Items = items

			// Emit event for Phase 3 (Inventory)
			payload := map[string]any{
				"po_id":       id,
				"branch_id":   updatedPO.BranchID,
				"supplier_id": updatedPO.SupplierID,
				"items":       items,
			}
			if err := s.outbox.Save(ctx, "procurement.order_received", payload); err != nil {
				return fmt.Errorf("saving to outbox: %w", err)
			}
		}

		return nil
	})

	if err != nil {
		return dto.POResponse{}, apperrors.Internal("status update failed", err)
	}

	return toPOResponse(updatedPO), nil
}

func isValidTransition(current, next string) bool {
	transitions := map[string][]string{
		domain.POStatusDraft:    {domain.POStatusPending, domain.POStatusRejected},
		domain.POStatusPending:  {domain.POStatusApproved, domain.POStatusRejected},
		domain.POStatusApproved: {domain.POStatusReceived, domain.POStatusRejected},
		domain.POStatusRejected: {},
		domain.POStatusReceived: {},
	}

	allowed, ok := transitions[current]
	if !ok {
		return false
	}

	for _, a := range allowed {
		if a == next {
			return true
		}
	}
	return false
}

func toPOResponse(po *domain.PurchaseOrder) dto.POResponse {
	items := make([]dto.POItemResponse, 0, len(po.Items))
	for _, item := range po.Items {
		items = append(items, dto.POItemResponse{
			ID:         item.ID,
			ProductID:  item.ProductID,
			Quantity:   item.Quantity,
			UnitPrice:  item.UnitPrice,
			TotalPrice: item.TotalPrice,
		})
	}

	return dto.POResponse{
		ID:          po.ID,
		SupplierID:  po.SupplierID,
		BranchID:    po.BranchID,
		Status:      po.Status,
		TotalAmount: po.TotalAmount,
		Note:        po.Note,
		CreatedAt:   po.CreatedAt,
		UpdatedAt:   po.UpdatedAt,
		Items:       items,
	}
}
