// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_notifications.sql

package notificationdb

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadByUser = `-- name: CountUnreadByUser :one
SELECT COUNT(*) FROM notification.user_notifications
WHERE user_id = $1 AND read_at IS NULL
`

// Hot path — bell-icon badge polled every ~10s. Hits the partial unread
// index so cost is independent of total notification count.
func (q *Queries) CountUnreadByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserNotifications = `-- name: CountUserNotifications :one
SELECT COUNT(*) FROM notification.user_notifications
WHERE user_id = $1
  AND (NOT $2::boolean
        OR ((read_at IS NULL) = $3::boolean))
`

type CountUserNotificationsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	FilterUnread bool      `json:"filter_unread"`
	IsUnread     bool      `json:"is_unread"`
}

func (q *Queries) CountUserNotifications(ctx context.Context, arg CountUserNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserNotifications, arg.UserID, arg.FilterUnread, arg.IsUnread)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserNotificationByID = `-- name: GetUserNotificationByID :one
SELECT id, user_id, type, title, body, data, read_at, created_at FROM notification.user_notifications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserNotificationByID(ctx context.Context, id uuid.UUID) (NotificationUserNotification, error) {
	row := q.db.QueryRow(ctx, getUserNotificationByID, id)
	var i NotificationUserNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertUserNotification = `-- name: InsertUserNotification :one
INSERT INTO notification.user_notifications (user_id, type, title, body, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, body, data, read_at, created_at
`

type InsertUserNotificationParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
	Title  string    `json:"title"`
	Body   string    `json:"body"`
	Data   []byte    `json:"data"`
}

func (q *Queries) InsertUserNotification(ctx context.Context, arg InsertUserNotificationParams) (NotificationUserNotification, error) {
	row := q.db.QueryRow(ctx, insertUserNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i NotificationUserNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, user_id, type, title, body, data, read_at, created_at FROM notification.user_notifications
WHERE user_id = $1
  AND (NOT $2::boolean
        OR ((read_at IS NULL) = $3::boolean))
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListUserNotificationsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	FilterUnread bool      `json:"filter_unread"`
	IsUnread     bool      `json:"is_unread"`
	Off          int32     `json:"off"`
	Lim          int32     `json:"lim"`
}

// The boolean "filter_unread" controls whether the query restricts to
// read/unread; when false, "is_unread" is ignored. Mirrors the active-
// filter pattern used in voucher + product list.
func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]NotificationUserNotification, error) {
	rows, err := q.db.Query(ctx, listUserNotifications,
		arg.UserID,
		arg.FilterUnread,
		arg.IsUnread,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationUserNotification{}
	for rows.Next() {
		var i NotificationUserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsReadByUser = `-- name: MarkAllNotificationsReadByUser :execrows
UPDATE notification.user_notifications
SET read_at = NOW()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsReadByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsReadByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notification.user_notifications
SET read_at = NOW()
WHERE id = $1 AND user_id = $2 AND read_at IS NULL
RETURNING id, user_id, type, title, body, data, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// User-scoped so an attacker can't mark someone else's notifications read
// (returns 0 rows if id belongs to another user → handler 404s).
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (NotificationUserNotification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i NotificationUserNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
