// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package cartdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const clearCartItems = `-- name: ClearCartItems :exec
DELETE FROM cart.cart_items
WHERE cart_id = $1
`

func (q *Queries) ClearCartItems(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCartItems, cartID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO cart.carts (user_id)
VALUES ($1)
RETURNING id, user_id, created_at, updated_at
`

func (q *Queries) CreateCart(ctx context.Context, userID uuid.UUID) (CartCart, error) {
	row := q.db.QueryRow(ctx, createCart, userID)
	var i CartCart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart.cart_items
WHERE cart_id = $1 AND product_id = $2
`

type DeleteCartItemParams struct {
	CartID    uuid.UUID `json:"cart_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.CartID, arg.ProductID)
	return err
}

const deleteCartItemByID = `-- name: DeleteCartItemByID :one
DELETE FROM cart.cart_items
WHERE id = $1 AND cart_id = $2
RETURNING id
`

type DeleteCartItemByIDParams struct {
	ID     uuid.UUID `json:"id"`
	CartID uuid.UUID `json:"cart_id"`
}

func (q *Queries) DeleteCartItemByID(ctx context.Context, arg DeleteCartItemByIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCartItemByID, arg.ID, arg.CartID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCartByID = `-- name: GetCartByID :one
SELECT id, user_id, created_at, updated_at FROM cart.carts
WHERE id = $1
`

func (q *Queries) GetCartByID(ctx context.Context, id uuid.UUID) (CartCart, error) {
	row := q.db.QueryRow(ctx, getCartByID, id)
	var i CartCart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByUser = `-- name: GetCartByUser :one
SELECT id, user_id, created_at, updated_at FROM cart.carts
WHERE user_id = $1
`

func (q *Queries) GetCartByUser(ctx context.Context, userID uuid.UUID) (CartCart, error) {
	row := q.db.QueryRow(ctx, getCartByUser, userID)
	var i CartCart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, cart_id, product_id, quantity, unit_price_snap, added_at FROM cart.cart_items
WHERE cart_id = $1
ORDER BY added_at ASC
`

func (q *Queries) ListCartItems(ctx context.Context, cartID uuid.UUID) ([]CartCartItem, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CartCartItem{}
	for rows.Next() {
		var i CartCartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPriceSnap,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCartItemQuantity = `-- name: SetCartItemQuantity :one
UPDATE cart.cart_items
SET quantity        = $3,
    unit_price_snap = $4,
    added_at        = NOW()
WHERE cart_id = $1 AND product_id = $2
RETURNING id, cart_id, product_id, quantity, unit_price_snap, added_at
`

type SetCartItemQuantityParams struct {
	CartID        uuid.UUID       `json:"cart_id"`
	ProductID     uuid.UUID       `json:"product_id"`
	Quantity      int32           `json:"quantity"`
	UnitPriceSnap decimal.Decimal `json:"unit_price_snap"`
}

func (q *Queries) SetCartItemQuantity(ctx context.Context, arg SetCartItemQuantityParams) (CartCartItem, error) {
	row := q.db.QueryRow(ctx, setCartItemQuantity,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPriceSnap,
	)
	var i CartCartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPriceSnap,
		&i.AddedAt,
	)
	return i, err
}

const setCartItemQuantityByID = `-- name: SetCartItemQuantityByID :one
UPDATE cart.cart_items
SET quantity = $3,
    added_at = NOW()
WHERE id = $1 AND cart_id = $2
RETURNING id, cart_id, product_id, quantity, unit_price_snap, added_at
`

type SetCartItemQuantityByIDParams struct {
	ID       uuid.UUID `json:"id"`
	CartID   uuid.UUID `json:"cart_id"`
	Quantity int32     `json:"quantity"`
}

// Cart-keyed update: cart_id in WHERE prevents touching another user's cart.
func (q *Queries) SetCartItemQuantityByID(ctx context.Context, arg SetCartItemQuantityByIDParams) (CartCartItem, error) {
	row := q.db.QueryRow(ctx, setCartItemQuantityByID, arg.ID, arg.CartID, arg.Quantity)
	var i CartCartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPriceSnap,
		&i.AddedAt,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart.cart_items (cart_id, product_id, quantity, unit_price_snap)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, product_id) DO UPDATE
SET quantity        = LEAST(cart.cart_items.quantity + EXCLUDED.quantity, 99),
    unit_price_snap = EXCLUDED.unit_price_snap,
    added_at        = NOW()
RETURNING id, cart_id, product_id, quantity, unit_price_snap, added_at
`

type UpsertCartItemParams struct {
	CartID        uuid.UUID       `json:"cart_id"`
	ProductID     uuid.UUID       `json:"product_id"`
	Quantity      int32           `json:"quantity"`
	UnitPriceSnap decimal.Decimal `json:"unit_price_snap"`
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartCartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPriceSnap,
	)
	var i CartCartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPriceSnap,
		&i.AddedAt,
	)
	return i, err
}
